<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Data\\DataAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'aggregateTracker',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Domain\\AggregateTracker',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'domainEventDispatcher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Domain\\DomainEventDispatcher',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'dataSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\DataSettings',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'persistenceExceptionTranslator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Exception\\PersistenceExceptionTranslator',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'transactionSynchronizationRegistry',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Transaction\\TransactionSynchronizationRegistry',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'transactionTemplate',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Transaction\\TransactionTemplate',
                        ],
                    ],
                ],
            ],
            6 => [
                'method' => 'transactionInterceptor',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Transaction\\TransactionInterceptor',
                        ],
                    ],
                ],
            ],
            7 => [
                'method' => 'transactionalManifest',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Transaction\\TransactionalManifest',
                        ],
                    ],
                ],
            ],
            8 => [
                'method' => 'proxyPlan',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Proxy\\ProxyPlan',
                        ],
                    ],
                ],
            ],
            9 => [
                'method' => 'interceptorRegistry',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Proxy\\InterceptorRegistry',
                        ],
                    ],
                ],
            ],
            10 => [
                'method' => 'proxyFactory',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Proxy\\ProxyFactory',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
