<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Data\\DataAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 1000,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'aggregateTracker',
                'returns' => 'Firefly\\Data\\Domain\\AggregateTracker',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            1 => [
                'method' => 'domainEventDispatcher',
                'returns' => 'Firefly\\Data\\Domain\\DomainEventDispatcher',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Data\\Domain\\AggregateTracker',
                    1 => 'Firefly\\Context\\Event\\ApplicationEventPublisher',
                ],
            ],
            2 => [
                'method' => 'dataSettings',
                'returns' => 'Firefly\\Data\\DataSettings',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            3 => [
                'method' => 'persistenceExceptionTranslator',
                'returns' => 'Firefly\\Data\\Exception\\PersistenceExceptionTranslator',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Data\\DataSettings',
                ],
            ],
            4 => [
                'method' => 'transactionTemplate',
                'returns' => 'Firefly\\Data\\Transaction\\TransactionTemplate',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Data\\Domain\\DomainEventDispatcher',
                    1 => 'Firefly\\Data\\Exception\\PersistenceExceptionTranslator',
                    2 => 'Firefly\\Data\\DataSettings',
                ],
            ],
            5 => [
                'method' => 'transactionInterceptor',
                'returns' => 'Firefly\\Data\\Transaction\\TransactionInterceptor',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Data\\Transaction\\TransactionTemplate',
                ],
            ],
            6 => [
                'method' => 'transactionalManifest',
                'returns' => 'Firefly\\Data\\Transaction\\TransactionalManifest',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Illuminate\\Contracts\\Container\\Container',
                ],
            ],
            7 => [
                'method' => 'proxyFactory',
                'returns' => 'Firefly\\Data\\Proxy\\ProxyFactory',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Data\\Transaction\\TransactionalBeanPostProcessor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Context\\Processor\\BeanPostProcessor',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Data\\Transaction\\TransactionalManifest',
            1 => 'Firefly\\Data\\Proxy\\ProxyFactory',
            2 => 'Firefly\\Data\\Transaction\\TransactionInterceptor',
        ],
    ],
];
