<?php

declare(strict_types=1);

namespace Firefly\Cli\Command\Make;

use Illuminate\Console\GeneratorCommand;

/**
 * `make:firefly-repository` — scaffolds a concrete #[Repository] bean extending the framework's
 * `Firefly\Data\Repository\EloquentRepository` (pyfly's `generate repository` parity).
 *
 * It used to generate a bare `interface X extends CrudRepository`, which was dead code the moment it was
 * written. Nothing in the framework synthesises an implementation for a repository interface (there is no
 * Spring-Data-style dynamic proxy here), so no binding ever existed for the generated type: injecting it
 * raised a BindingResolutionException, and ComponentScanner skipped it outright — `describe()` returns null
 * for `$reflection->isInterface()`, so it was not even in the component manifest to bind. CrudRepository's
 * own docblock says as much: "EloquentRepository is the Eloquent-backed implementation; app repositories
 * extend that, not this interface directly."
 *
 * The generated class therefore mirrors the framework's own WidgetRepository fixture: a #[Repository]
 * stereotype (so the component scan registers it as a singleton bean), `extends EloquentRepository`, and a
 * `$model` class-string the developer repoints at their own model. It is deliberately not `final` — a
 * #[Transactional] proxy generated by firefly:cache extends the target class.
 */
final class MakeRepositoryCommand extends GeneratorCommand
{
    /** @var string */
    protected $name = 'make:firefly-repository';

    /** @var string */
    protected $description = 'Create a Firefly #[Repository] (extends EloquentRepository).';

    /** @var string */
    protected $type = 'Firefly repository';

    protected function getStub(): string
    {
        return __DIR__.'/../../../stubs/repository.stub';
    }
}
