<?php

declare(strict_types=1);

namespace Firefly\Data\Transaction;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/**
 * Mirrors the scheduling ScheduledManifestCompiler: var_export of the TransactionalManifest's pure-array form
 * into a require-able PHP file.
 */
final class TransactionalManifestCompiler
{
    public function compile(TransactionalManifest $manifest): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/data. Do not edit.\n\nreturn "
            .var_export($manifest->toArray(), true)
            .";\n";
    }

    public function write(TransactionalManifest $manifest, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($manifest)) === false) {
            throw new ConfigurationException("Could not write transactional manifest to {$path}.");
        }
    }
}
