<?php

declare(strict_types=1);

namespace Firefly\Container\Scanner;

use Firefly\Container\Descriptor\ComponentDescriptor;
use Firefly\Kernel\Exception\Framework\ConfigurationException;

final class ManifestCompiler
{
    /**
     * @param  list<ComponentDescriptor>  $components
     */
    public function compile(array $components): string
    {
        $rows = array_map(static fn (ComponentDescriptor $c): array => $c->toArray(), $components);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/container. Do not edit.\n\nreturn "
            .var_export($rows, true)
            .";\n";
    }

    /**
     * @param  list<ComponentDescriptor>  $components
     */
    public function write(array $components, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($components)) === false) {
            throw new ConfigurationException("Could not write component manifest to {$path}.");
        }
    }
}
