<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\OpenApi\\OpenApiAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 1000,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'openApiProperties',
                'returns' => 'Firefly\\OpenApi\\OpenApiProperties',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            1 => [
                'method' => 'constraintSchemaMapper',
                'returns' => 'Firefly\\OpenApi\\Schema\\ConstraintSchemaMapper',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            2 => [
                'method' => 'dtoSchemaFactory',
                'returns' => 'Firefly\\OpenApi\\Schema\\DtoSchemaFactory',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            3 => [
                'method' => 'operationFactory',
                'returns' => 'Firefly\\OpenApi\\Generator\\OperationFactory',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            4 => [
                'method' => 'openApiGenerator',
                'returns' => 'Firefly\\OpenApi\\Generator\\OpenApiGenerator',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            5 => [
                'method' => 'viewerPage',
                'returns' => 'Firefly\\OpenApi\\Web\\ViewerPage',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
        ],
        'lazy' => false,
    ],
];
