<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\OpenApi\\OpenApiAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'openApiProperties',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\OpenApi\\OpenApiProperties',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'constraintSchemaMapper',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\OpenApi\\Schema\\ConstraintSchemaMapper',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'dtoSchemaFactory',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\OpenApi\\Schema\\DtoSchemaFactory',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'operationFactory',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\OpenApi\\Generator\\OperationFactory',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'openApiGenerator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\OpenApi\\Generator\\OpenApiGenerator',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'viewerPage',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\OpenApi\\Web\\ViewerPage',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
