<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Resilience\\Method\\ResilienceAdviceSource',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Data\\Proxy\\AdviceSource',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Resilience\\ResilienceAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 1000,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'resilienceStore',
                'returns' => 'Firefly\\Resilience\\Store\\ResilienceStore',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Illuminate\\Contracts\\Cache\\Repository',
                    1 => 'Firefly\\Config\\Config',
                ],
            ],
            1 => [
                'method' => 'resilienceRegistry',
                'returns' => 'Firefly\\Resilience\\ResilienceRegistry',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                    1 => 'Firefly\\Resilience\\Store\\ResilienceStore',
                ],
            ],
            2 => [
                'method' => 'resilienceMethodInterceptor',
                'returns' => 'Firefly\\Resilience\\Method\\ResilienceMethodInterceptor',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Resilience\\ResilienceRegistry',
                    1 => 'Firefly\\Config\\Config',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
];
