<?php

declare(strict_types=1);

namespace Firefly\Web\Exception;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/**
 * The missing half of the #[ControllerAdvice] / #[ExceptionHandler] contract.
 *
 * RouteScanner::scanExceptionHandlers() has always been fully implemented, and ExceptionHandlerDescriptor has
 * always carried toArray()/fromArray() — but nothing ever compiled the result, so firefly:cache emitted no
 * artifact and ExceptionHandlerRegistry was constructed empty in every real boot. Every #[ControllerAdvice] a
 * user wrote was silently dead while docs and the book taught it as working. This mirrors RouteManifestCompiler
 * exactly: var_export of descriptor rows into a require-able PHP file.
 */
final class ExceptionHandlerManifestCompiler
{
    /**
     * @param  list<ExceptionHandlerDescriptor>  $handlers
     */
    public function compile(array $handlers): string
    {
        $rows = array_map(static fn (ExceptionHandlerDescriptor $h): array => $h->toArray(), $handlers);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/web. Do not edit.\n\nreturn "
            .var_export($rows, true)
            .";\n";
    }

    /**
     * @param  list<ExceptionHandlerDescriptor>  $handlers
     */
    public function write(array $handlers, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($handlers)) === false) {
            throw new ConfigurationException("Could not write exception-handler manifest to {$path}.");
        }
    }
}
