<?php

declare(strict_types=1);

namespace Firefly\Cli\Cache;

use Firefly\AutoConfigure\Assembly\AutoConfigManifestCompiler;
use Firefly\Config\Scanner\ConfigManifestCompiler;
use Firefly\Config\Scanner\ConfigPropertiesScanner;
use Firefly\Cqrs\Handler\HandlerManifestCompiler;
use Firefly\Cqrs\Scanner\HandlerScanner;
use Firefly\Data\Proxy\ProxyClassGenerator;
use Firefly\Data\Scanner\TransactionalScanner;
use Firefly\Data\Transaction\TransactionalManifestCompiler;
use Firefly\Eda\Listener\EventListenerManifestCompiler;
use Firefly\Eda\Scanner\EventListenerScanner;
use Firefly\Messaging\Listener\MessageListenerManifestCompiler;
use Firefly\Messaging\Scanner\MessageListenerScanner;
use Firefly\Scheduling\Scanner\ScheduledScanner;
use Firefly\Scheduling\Schedule\ScheduledManifestCompiler;
use Firefly\Security\Access\Method\SecurityMethodManifestCompiler;
use Firefly\Security\Scanner\MethodSecurityScanner;
use Firefly\Validation\Constraint\ConstraintManifestCompiler;
use Firefly\Web\Exception\ExceptionHandlerManifestCompiler;
use Firefly\Web\Route\RouteManifestCompiler;
use Firefly\Web\Route\RouteScanner;

/**
 * Orchestrates every settled package's EXISTING scanner->compiler pair (D4 DIRECT DEPENDENCY — no new port,
 * zero edits to settled/frozen src) to emit the app's compiled manifests into $dir. Deterministic + idempotent.
 */
final class ManifestCacheWriter
{
    /**
     * The full firefly:cache emission: every app manifest (writeManifests) PLUS the #[Transactional] proxy class
     * files + their classmap (writeProxies). This is what CacheCommand drives and what the cached boot consumes.
     *
     * @param  array<string,string>  $psr4
     */
    public function write(array $psr4, string $dir): CacheReport
    {
        $report = $this->writeManifests($psr4, $dir);
        $count = $this->writeProxies($psr4, $dir);

        return new CacheReport([...$report->files, $dir.'/'.FireflyCachePaths::PROXY_MAP], $count);
    }

    /**
     * Emits one `proxies/<mangled>.php` file per #[Transactional] class (generated by the SAME reflection-free
     * ProxyClassGenerator the runtime uses) plus a `proxies.php` classmap keyed by proxy FQCN so
     * FireflyCacheServiceProvider can autoload them before TransactionalBeanPostProcessor's class_exists() check.
     *
     * @param  array<string,string>  $psr4
     */
    public function writeProxies(array $psr4, string $dir): int
    {
        $proxyDir = $dir.'/'.FireflyCachePaths::PROXY_DIR;
        if (! is_dir($proxyDir)) {
            mkdir($proxyDir, 0o755, true);
        }

        $generator = new ProxyClassGenerator;
        $map = [];

        foreach ((new TransactionalScanner)->scanProxyMethods($psr4) as $targetClass => $methods) {
            $source = $generator->generate($targetClass, $methods);
            $proxyClass = $targetClass.'__FireflyTransactionalProxy';
            $file = $proxyDir.'/'.str_replace('\\', '_', $targetClass).'.php';
            file_put_contents($file, $source);
            $map[$proxyClass] = $file;
        }

        file_put_contents(
            $dir.'/'.FireflyCachePaths::PROXY_MAP,
            "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/cli. Do not edit.\n\nreturn ".var_export($map, true).";\n",
        );

        return count($map);
    }

    /**
     * @param  array<string,string>  $psr4
     */
    public function writeManifests(array $psr4, string $dir): CacheReport
    {
        if (! is_dir($dir)) {
            mkdir($dir, 0o755, true);
        }

        $files = [];

        // container + context + autoconfigure (folded): one call emits both component + context manifests.
        (new AutoConfigManifestCompiler)->write(
            $psr4,
            $files[] = $dir.'/'.FireflyCachePaths::COMPONENT,
            $files[] = $dir.'/'.FireflyCachePaths::CONTEXT,
        );

        // config — emits config-properties.php; NOT consumed via component/context (that claim is false).
        // Bound by FireflyCacheServiceProvider via ConfigRegistrar on the CACHED path only (Task 3);
        // dev (uncached) boot still leaves #[ConfigProperties] unbound — pre-existing framework limitation.
        (new ConfigManifestCompiler)->write(
            (new ConfigPropertiesScanner)->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::CONFIG_PROPERTIES,
        );

        // web
        $routeScanner = new RouteScanner;
        (new RouteManifestCompiler)->write(
            $routeScanner->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::ROUTES,
        );

        // web — #[ControllerAdvice]/#[ExceptionHandler]. scanExceptionHandlers() has always existed but was
        // never compiled, so ExceptionHandlerRegistry was empty in every real boot and every #[ControllerAdvice]
        // was silently dead. Emitting the artifact is the other half of that fix.
        (new ExceptionHandlerManifestCompiler)->write(
            $routeScanner->scanExceptionHandlers($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::EXCEPTION_HANDLERS,
        );

        // validation — compiles from an explicit class list, not a PSR-4 scan (SPECIAL).
        (new ConstraintManifestCompiler)->write(
            (new ClassEnumerator)->enumerate($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::CONSTRAINTS,
        );

        // cqrs — 3-arg write (handlers + destinations + path) (SPECIAL).
        $handlers = (new HandlerScanner)->scan($psr4);
        (new HandlerManifestCompiler)->write(
            $handlers['handlers'],
            $handlers['destinations'],
            $files[] = $dir.'/'.FireflyCachePaths::HANDLERS,
        );

        // eda
        (new EventListenerManifestCompiler)->write(
            (new EventListenerScanner)->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::EVENT_LISTENERS,
        );

        // messaging
        (new MessageListenerManifestCompiler)->write(
            (new MessageListenerScanner)->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::MESSAGE_LISTENERS,
        );

        // scheduling
        (new ScheduledManifestCompiler)->write(
            (new ScheduledScanner)->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::SCHEDULED,
        );

        // security
        (new SecurityMethodManifestCompiler)->write(
            (new MethodSecurityScanner)->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::SECURITY_METHODS,
        );

        // data — transactional manifest data (proxy CLASS files added in Task 3).
        (new TransactionalManifestCompiler)->write(
            (new TransactionalScanner)->scan($psr4),
            $files[] = $dir.'/'.FireflyCachePaths::TRANSACTIONAL,
        );

        return new CacheReport($files);
    }
}
