<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Observability\\Endpoint\\MetricsEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => true,
    ],
    1 => [
        'class' => 'Firefly\\Observability\\Endpoint\\PrometheusEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => true,
    ],
    2 => [
        'class' => 'Firefly\\Observability\\Web\\MetricsFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -100,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => true,
    ],
];
