<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Observability\\Endpoint\\MetricsEndpoint',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.observability.metrics.enabled',
                    1 => 'true',
                    2 => true,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Observability\\Endpoint\\PrometheusEndpoint',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.observability.metrics.enabled',
                    1 => 'true',
                    2 => true,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
];
