<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Observability\\Endpoint\\MetricsEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => true,
    ],
    1 => [
        'class' => 'Firefly\\Observability\\Endpoint\\PrometheusEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => true,
    ],
    2 => [
        'class' => 'Firefly\\Observability\\ObservabilityAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 500,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'meterRegistry',
                'returns' => 'Firefly\\Observability\\Metrics\\MeterRegistry',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            1 => [
                'method' => 'metricsRecorder',
                'returns' => 'Firefly\\Observability\\Metrics\\MetricsRecorder',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            2 => [
                'method' => 'prometheusTextFormat',
                'returns' => 'Firefly\\Observability\\Prometheus\\PrometheusTextFormat',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            3 => [
                'method' => 'tracer',
                'returns' => 'Firefly\\Observability\\Tracing\\Tracer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            4 => [
                'method' => 'cqrsMetrics',
                'returns' => 'Firefly\\Cqrs\\Metrics\\CqrsMetrics',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
        ],
        'lazy' => false,
    ],
    3 => [
        'class' => 'Firefly\\Observability\\Web\\MetricsFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -100,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => true,
    ],
];
