<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return array (
  0 => 
  array (
    'class' => 'Firefly\\Security\\Actuator\\SecurityActuatorAutoConfiguration',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnClass',
        'args' => 
        array (
          0 => 'Firefly\\Actuator\\Health\\HealthDetailsAuthorizer',
        ),
      ),
    ),
    'beanConditions' => 
    array (
      0 => 
      array (
        'method' => 'healthDetailsAuthorizer',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Actuator\\Health\\HealthDetailsAuthorizer',
            ),
          ),
        ),
      ),
    ),
  ),
  1 => 
  array (
    'class' => 'Firefly\\Security\\OAuth2\\OAuth2ResourceServerFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.oauth2.resource_server.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  2 => 
  array (
    'class' => 'Firefly\\Security\\OpenApi\\MethodSecurityRequirementContributor',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnClass',
        'args' => 
        array (
          0 => 'Firefly\\OpenApi\\Security\\SecurityRequirementContributor',
        ),
      ),
      1 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  3 => 
  array (
    'class' => 'Firefly\\Security\\SecurityAutoConfiguration',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
    ),
    'beanConditions' => 
    array (
      0 => 
      array (
        'method' => 'passwordEncoder',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Password\\PasswordEncoder',
            ),
          ),
        ),
      ),
      1 => 
      array (
        'method' => 'userDetailsService',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\User\\UserDetailsService',
            ),
          ),
        ),
      ),
      2 => 
      array (
        'method' => 'roleHierarchy',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\RoleHierarchy',
            ),
          ),
        ),
      ),
      3 => 
      array (
        'method' => 'permissionEvaluator',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\PermissionEvaluator',
            ),
          ),
        ),
      ),
      4 => 
      array (
        'method' => 'securityExpressionEvaluator',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
            ),
          ),
        ),
      ),
      5 => 
      array (
        'method' => 'authenticationManager',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Authentication\\AuthenticationManager',
            ),
          ),
        ),
      ),
      6 => 
      array (
        'method' => 'authorizationChecker',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\AuthorizationChecker',
            ),
          ),
        ),
      ),
      7 => 
      array (
        'method' => 'methodSecurityEvaluator',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\Method\\MethodSecurityEvaluator',
            ),
          ),
        ),
      ),
      8 => 
      array (
        'method' => 'methodSecurityInterceptor',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.method.enabled',
              1 => 'true',
              2 => true,
            ),
          ),
          2 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\Method\\MethodSecurityInterceptor',
            ),
          ),
        ),
      ),
      9 => 
      array (
        'method' => 'methodSecurityMessageEnforcer',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
            ),
          ),
        ),
      ),
      10 => 
      array (
        'method' => 'commandAuthorizer',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
            ),
          ),
        ),
      ),
      11 => 
      array (
        'method' => 'queryAuthorizer',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
            ),
          ),
        ),
      ),
      12 => 
      array (
        'method' => 'auditorAware',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Data\\Repository\\Auditing\\AuditorAware',
            ),
          ),
        ),
      ),
      13 => 
      array (
        'method' => 'authenticationEventPublisher',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
            ),
          ),
        ),
      ),
      14 => 
      array (
        'method' => 'sessionSecuritySettings',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Session\\SessionSecuritySettings',
            ),
          ),
        ),
      ),
      15 => 
      array (
        'method' => 'securityContextRepository',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Session\\SecurityContextRepository',
            ),
          ),
        ),
      ),
      16 => 
      array (
        'method' => 'formLoginSettings',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\Settings\\FormLoginSettings',
            ),
          ),
        ),
      ),
      17 => 
      array (
        'method' => 'httpBasicSettings',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\Settings\\HttpBasicSettings',
            ),
          ),
        ),
      ),
      18 => 
      array (
        'method' => 'logoutSettings',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\Settings\\LogoutSettings',
            ),
          ),
        ),
      ),
      19 => 
      array (
        'method' => 'rememberMeSettings',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\Settings\\RememberMeSettings',
            ),
          ),
        ),
      ),
      20 => 
      array (
        'method' => 'rememberMeServices',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.remember_me.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          2 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\RememberMe\\RememberMeServices',
            ),
          ),
        ),
      ),
      21 => 
      array (
        'method' => 'authenticationEntryPoint',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.http.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          2 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\EntryPoint\\AuthenticationEntryPoint',
            ),
          ),
        ),
      ),
      22 => 
      array (
        'method' => 'sessionCsrf',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Web\\Csrf\\SessionCsrf',
            ),
          ),
        ),
      ),
      23 => 
      array (
        'method' => 'jwtService',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.jwt.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Jwt\\JwtService',
            ),
          ),
        ),
      ),
      24 => 
      array (
        'method' => 'httpSecurity',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.http.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\Access\\HttpSecurity',
            ),
          ),
        ),
      ),
      25 => 
      array (
        'method' => 'jwksProvider',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.security.oauth2.resource_server.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\Security\\OAuth2\\JwksProvider',
            ),
          ),
        ),
      ),
    ),
  ),
  4 => 
  array (
    'class' => 'Firefly\\Security\\Session\\SecurityContextPersistenceFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  5 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Basic\\HttpBasicFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
      1 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.http_basic.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  6 => 
  array (
    'class' => 'Firefly\\Security\\Web\\CsrfFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.csrf.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  7 => 
  array (
    'class' => 'Firefly\\Security\\Web\\HttpSecurityFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
      1 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.http.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  8 => 
  array (
    'class' => 'Firefly\\Security\\Web\\JwtAuthenticationFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.jwt.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  9 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Login\\FormLoginFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
      1 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.form_login.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  10 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Logout\\LogoutFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  11 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Logout\\LogoutHandler',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  12 => 
  array (
    'class' => 'Firefly\\Security\\Web\\RememberMe\\RememberMeAuthenticationFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  13 => 
  array (
    'class' => 'Firefly\\Security\\Web\\SecurityHeadersFilter',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.security.headers.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
);
