<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Security\\OAuth2\\OAuth2ResourceServerFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -85,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Security\\OAuth2\\JwksProvider',
            1 => 'Firefly\\Config\\Config',
        ],
    ],
    1 => [
        'class' => 'Firefly\\Security\\SecurityAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 500,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'passwordEncoder',
                'returns' => 'Firefly\\Security\\Password\\PasswordEncoder',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            1 => [
                'method' => 'userDetailsService',
                'returns' => 'Firefly\\Security\\User\\UserDetailsService',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            2 => [
                'method' => 'roleHierarchy',
                'returns' => 'Firefly\\Security\\Access\\RoleHierarchy',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            3 => [
                'method' => 'permissionEvaluator',
                'returns' => 'Firefly\\Security\\Access\\PermissionEvaluator',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            4 => [
                'method' => 'securityExpressionEvaluator',
                'returns' => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            5 => [
                'method' => 'authenticationManager',
                'returns' => 'Firefly\\Security\\Authentication\\AuthenticationManager',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\User\\UserDetailsService',
                    1 => 'Firefly\\Security\\Password\\PasswordEncoder',
                ],
            ],
            6 => [
                'method' => 'authorizationChecker',
                'returns' => 'Firefly\\Security\\Access\\AuthorizationChecker',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
                    1 => 'Firefly\\Security\\Access\\RoleHierarchy',
                    2 => 'Firefly\\Security\\Access\\PermissionEvaluator',
                ],
            ],
            7 => [
                'method' => 'methodSecurityMessageEnforcer',
                'returns' => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Cqrs\\Handler\\HandlerManifest',
                    1 => 'Firefly\\Security\\Access\\Method\\SecurityMethodManifest',
                    2 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
                    3 => 'Firefly\\Security\\Access\\RoleHierarchy',
                    4 => 'Firefly\\Security\\Access\\PermissionEvaluator',
                ],
            ],
            8 => [
                'method' => 'commandAuthorizer',
                'returns' => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
                ],
            ],
            9 => [
                'method' => 'queryAuthorizer',
                'returns' => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
                ],
            ],
            10 => [
                'method' => 'auditorAware',
                'returns' => 'Firefly\\Data\\Repository\\Auditing\\AuditorAware',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            11 => [
                'method' => 'jwtService',
                'returns' => 'Firefly\\Security\\Jwt\\JwtService',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            12 => [
                'method' => 'httpSecurity',
                'returns' => 'Firefly\\Security\\Access\\HttpSecurity',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            13 => [
                'method' => 'jwksProvider',
                'returns' => 'Firefly\\Security\\OAuth2\\JwksProvider',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                    1 => 'Illuminate\\Container\\Container',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    2 => [
        'class' => 'Firefly\\Security\\Web\\CsrfFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -80,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Config\\Config',
        ],
    ],
    3 => [
        'class' => 'Firefly\\Security\\Web\\HttpSecurityFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -70,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Security\\Access\\HttpSecurity',
            1 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
            2 => 'Firefly\\Security\\Access\\RoleHierarchy',
            3 => 'Firefly\\Security\\Access\\PermissionEvaluator',
            4 => 'Firefly\\Config\\Config',
        ],
    ],
    4 => [
        'class' => 'Firefly\\Security\\Web\\JwtAuthenticationFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -90,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Security\\Jwt\\JwtService',
            1 => 'Firefly\\Config\\Config',
        ],
    ],
    5 => [
        'class' => 'Firefly\\Security\\Web\\SecurityHeadersFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -95,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Config\\Config',
        ],
    ],
];
