<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Security\\OAuth2\\OAuth2ResourceServerFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.resource_server.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Security\\SecurityAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'passwordEncoder',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Password\\PasswordEncoder',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'userDetailsService',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\User\\UserDetailsService',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'roleHierarchy',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\RoleHierarchy',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'permissionEvaluator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\PermissionEvaluator',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'securityExpressionEvaluator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'authenticationManager',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Authentication\\AuthenticationManager',
                        ],
                    ],
                ],
            ],
            6 => [
                'method' => 'authorizationChecker',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\AuthorizationChecker',
                        ],
                    ],
                ],
            ],
            7 => [
                'method' => 'methodSecurityEvaluator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\Method\\MethodSecurityEvaluator',
                        ],
                    ],
                ],
            ],
            8 => [
                'method' => 'methodSecurityInterceptor',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.method.enabled',
                            1 => 'true',
                            2 => true,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\Method\\MethodSecurityInterceptor',
                        ],
                    ],
                ],
            ],
            9 => [
                'method' => 'methodSecurityMessageEnforcer',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
                        ],
                    ],
                ],
            ],
            10 => [
                'method' => 'commandAuthorizer',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
                        ],
                    ],
                ],
            ],
            11 => [
                'method' => 'queryAuthorizer',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
                        ],
                    ],
                ],
            ],
            12 => [
                'method' => 'auditorAware',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Data\\Repository\\Auditing\\AuditorAware',
                        ],
                    ],
                ],
            ],
            13 => [
                'method' => 'authenticationEventPublisher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
                        ],
                    ],
                ],
            ],
            14 => [
                'method' => 'sessionSecuritySettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Session\\SessionSecuritySettings',
                        ],
                    ],
                ],
            ],
            15 => [
                'method' => 'securityContextRepository',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Session\\SecurityContextRepository',
                        ],
                    ],
                ],
            ],
            16 => [
                'method' => 'formLoginSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Settings\\FormLoginSettings',
                        ],
                    ],
                ],
            ],
            17 => [
                'method' => 'httpBasicSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Settings\\HttpBasicSettings',
                        ],
                    ],
                ],
            ],
            18 => [
                'method' => 'logoutSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Settings\\LogoutSettings',
                        ],
                    ],
                ],
            ],
            19 => [
                'method' => 'rememberMeSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Settings\\RememberMeSettings',
                        ],
                    ],
                ],
            ],
            20 => [
                'method' => 'authenticationEntryPoint',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.http.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\EntryPoint\\AuthenticationEntryPoint',
                        ],
                    ],
                ],
            ],
            21 => [
                'method' => 'sessionCsrf',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Csrf\\SessionCsrf',
                        ],
                    ],
                ],
            ],
            22 => [
                'method' => 'jwtService',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.jwt.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Jwt\\JwtService',
                        ],
                    ],
                ],
            ],
            23 => [
                'method' => 'httpSecurity',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.http.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Access\\HttpSecurity',
                        ],
                    ],
                ],
            ],
            24 => [
                'method' => 'jwksProvider',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.resource_server.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\JwksProvider',
                        ],
                    ],
                ],
            ],
        ],
    ],
    2 => [
        'class' => 'Firefly\\Security\\Session\\SecurityContextPersistenceFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    3 => [
        'class' => 'Firefly\\Security\\Web\\CsrfFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.csrf.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    4 => [
        'class' => 'Firefly\\Security\\Web\\HttpSecurityFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            1 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.http.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    5 => [
        'class' => 'Firefly\\Security\\Web\\JwtAuthenticationFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.jwt.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    6 => [
        'class' => 'Firefly\\Security\\Web\\Login\\FormLoginFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    7 => [
        'class' => 'Firefly\\Security\\Web\\SecurityHeadersFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.headers.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
];
