<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return array (
  0 => 
  array (
    'class' => 'Firefly\\Security\\Access\\Method\\MethodSecurityAdviceSource',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 0,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Data\\Proxy\\AdviceSource',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
    ),
  ),
  1 => 
  array (
    'class' => 'Firefly\\Security\\Actuator\\SecurityActuatorAutoConfiguration',
    'stereotype' => 'configuration',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 400,
    'qualifier' => NULL,
    'interfaces' => 
    array (
    ),
    'beans' => 
    array (
      0 => 
      array (
        'method' => 'healthDetailsAuthorizer',
        'returns' => 'Firefly\\Actuator\\Health\\HealthDetailsAuthorizer',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
          1 => 'Firefly\\Security\\Access\\RoleHierarchy',
          2 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
    ),
    'lazy' => false,
    'dependencies' => 
    array (
    ),
  ),
  2 => 
  array (
    'class' => 'Firefly\\Security\\OAuth2\\OAuth2ResourceServerFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -85,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\OAuth2\\JwksProvider',
      1 => 'Firefly\\Config\\Config',
    ),
  ),
  3 => 
  array (
    'class' => 'Firefly\\Security\\OpenApi\\MethodSecurityRequirementContributor',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 0,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\OpenApi\\Security\\SecurityRequirementContributor',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Access\\Method\\SecurityMethodManifest',
      1 => 'Firefly\\Config\\Config',
    ),
  ),
  4 => 
  array (
    'class' => 'Firefly\\Security\\SecurityAutoConfiguration',
    'stereotype' => 'configuration',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 500,
    'qualifier' => NULL,
    'interfaces' => 
    array (
    ),
    'beans' => 
    array (
      0 => 
      array (
        'method' => 'passwordEncoder',
        'returns' => 'Firefly\\Security\\Password\\PasswordEncoder',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
      1 => 
      array (
        'method' => 'userDetailsService',
        'returns' => 'Firefly\\Security\\User\\UserDetailsService',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      2 => 
      array (
        'method' => 'roleHierarchy',
        'returns' => 'Firefly\\Security\\Access\\RoleHierarchy',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      3 => 
      array (
        'method' => 'permissionEvaluator',
        'returns' => 'Firefly\\Security\\Access\\PermissionEvaluator',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
      4 => 
      array (
        'method' => 'securityExpressionEvaluator',
        'returns' => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
      5 => 
      array (
        'method' => 'authenticationManager',
        'returns' => 'Firefly\\Security\\Authentication\\AuthenticationManager',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => true,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\User\\UserDetailsService',
          1 => 'Firefly\\Security\\Password\\PasswordEncoder',
        ),
      ),
      6 => 
      array (
        'method' => 'authorizationChecker',
        'returns' => 'Firefly\\Security\\Access\\AuthorizationChecker',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
          1 => 'Firefly\\Security\\Access\\RoleHierarchy',
          2 => 'Firefly\\Security\\Access\\PermissionEvaluator',
        ),
      ),
      7 => 
      array (
        'method' => 'methodSecurityEvaluator',
        'returns' => 'Firefly\\Security\\Access\\Method\\MethodSecurityEvaluator',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
          1 => 'Firefly\\Security\\Access\\RoleHierarchy',
          2 => 'Firefly\\Security\\Access\\PermissionEvaluator',
          3 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
          4 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
      8 => 
      array (
        'method' => 'methodSecurityInterceptor',
        'returns' => 'Firefly\\Security\\Access\\Method\\MethodSecurityInterceptor',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\Access\\Method\\MethodSecurityEvaluator',
          1 => 'Firefly\\Config\\Config',
        ),
      ),
      9 => 
      array (
        'method' => 'methodSecurityMessageEnforcer',
        'returns' => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Cqrs\\Handler\\HandlerManifest',
          1 => 'Firefly\\Security\\Access\\Method\\SecurityMethodManifest',
          2 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
          3 => 'Firefly\\Security\\Access\\RoleHierarchy',
          4 => 'Firefly\\Security\\Access\\PermissionEvaluator',
          5 => 'Firefly\\Config\\Config',
          6 => 'Psr\\Log\\LoggerInterface',
          7 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
        ),
      ),
      10 => 
      array (
        'method' => 'commandAuthorizer',
        'returns' => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
        ),
      ),
      11 => 
      array (
        'method' => 'queryAuthorizer',
        'returns' => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\Cqrs\\MethodSecurityMessageEnforcer',
        ),
      ),
      12 => 
      array (
        'method' => 'auditorAware',
        'returns' => 'Firefly\\Data\\Repository\\Auditing\\AuditorAware',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
      13 => 
      array (
        'method' => 'authenticationEventPublisher',
        'returns' => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Context\\Event\\ApplicationEventPublisher',
        ),
      ),
      14 => 
      array (
        'method' => 'sessionSecuritySettings',
        'returns' => 'Firefly\\Security\\Session\\SessionSecuritySettings',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      15 => 
      array (
        'method' => 'securityContextRepository',
        'returns' => 'Firefly\\Security\\Session\\SecurityContextRepository',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
      16 => 
      array (
        'method' => 'formLoginSettings',
        'returns' => 'Firefly\\Security\\Web\\Settings\\FormLoginSettings',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      17 => 
      array (
        'method' => 'httpBasicSettings',
        'returns' => 'Firefly\\Security\\Web\\Settings\\HttpBasicSettings',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      18 => 
      array (
        'method' => 'logoutSettings',
        'returns' => 'Firefly\\Security\\Web\\Settings\\LogoutSettings',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      19 => 
      array (
        'method' => 'rememberMeSettings',
        'returns' => 'Firefly\\Security\\Web\\Settings\\RememberMeSettings',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      20 => 
      array (
        'method' => 'rememberMeServices',
        'returns' => 'Firefly\\Security\\Web\\RememberMe\\RememberMeServices',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Security\\Web\\Settings\\RememberMeSettings',
          1 => 'Firefly\\Security\\User\\UserDetailsService',
          2 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
      21 => 
      array (
        'method' => 'authenticationEntryPoint',
        'returns' => 'Firefly\\Security\\Web\\EntryPoint\\AuthenticationEntryPoint',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
          1 => 'Firefly\\Security\\Web\\Settings\\FormLoginSettings',
          2 => 'Firefly\\Security\\Web\\Settings\\HttpBasicSettings',
          3 => 'Firefly\\Web\\Error\\ErrorPageRenderer',
          4 => 'Firefly\\Web\\Exception\\ProblemDetailsRenderer',
        ),
      ),
      22 => 
      array (
        'method' => 'sessionCsrf',
        'returns' => 'Firefly\\Security\\Web\\Csrf\\SessionCsrf',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Illuminate\\Container\\Container',
        ),
      ),
      23 => 
      array (
        'method' => 'jwtService',
        'returns' => 'Firefly\\Security\\Jwt\\JwtService',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      24 => 
      array (
        'method' => 'httpSecurity',
        'returns' => 'Firefly\\Security\\Access\\HttpSecurity',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      25 => 
      array (
        'method' => 'jwksProvider',
        'returns' => 'Firefly\\Security\\OAuth2\\JwksProvider',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
          1 => 'Illuminate\\Container\\Container',
        ),
      ),
    ),
    'lazy' => false,
    'dependencies' => 
    array (
    ),
  ),
  5 => 
  array (
    'class' => 'Firefly\\Security\\Session\\SecurityContextPersistenceFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -94,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Session\\SecurityContextRepository',
      1 => 'Firefly\\Security\\Session\\SessionSecuritySettings',
      2 => 'Firefly\\Config\\Config',
    ),
  ),
  6 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Basic\\HttpBasicFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -91,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Web\\Settings\\HttpBasicSettings',
      1 => 'Firefly\\Security\\Authentication\\AuthenticationManager',
      2 => 'Firefly\\Security\\Web\\EntryPoint\\BasicAuthenticationEntryPoint',
      3 => 'Firefly\\Security\\Session\\SecurityContextRepository',
      4 => 'Firefly\\Security\\Session\\SessionSecuritySettings',
      5 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
      6 => 'Firefly\\Config\\Config',
    ),
  ),
  7 => 
  array (
    'class' => 'Firefly\\Security\\Web\\CsrfFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -80,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Config\\Config',
      1 => 'Firefly\\Security\\Web\\Csrf\\SessionCsrf',
    ),
  ),
  8 => 
  array (
    'class' => 'Firefly\\Security\\Web\\HttpSecurityFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -70,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Access\\HttpSecurity',
      1 => 'Firefly\\Security\\Access\\Expression\\SecurityExpressionEvaluator',
      2 => 'Firefly\\Security\\Access\\RoleHierarchy',
      3 => 'Firefly\\Security\\Access\\PermissionEvaluator',
      4 => 'Firefly\\Config\\Config',
      5 => 'Firefly\\Security\\Web\\EntryPoint\\AuthenticationEntryPoint',
      6 => 'Firefly\\Security\\Web\\Settings\\FormLoginSettings',
      7 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
    ),
  ),
  9 => 
  array (
    'class' => 'Firefly\\Security\\Web\\JwtAuthenticationFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -90,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Jwt\\JwtService',
      1 => 'Firefly\\Config\\Config',
    ),
  ),
  10 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Login\\FormLoginFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -92,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Web\\Settings\\FormLoginSettings',
      1 => 'Firefly\\Security\\Session\\SessionSecuritySettings',
      2 => 'Firefly\\Security\\Authentication\\AuthenticationManager',
      3 => 'Firefly\\Security\\Session\\SecurityContextRepository',
      4 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
      5 => 'Firefly\\Security\\Web\\Csrf\\SessionCsrf',
      6 => 'Illuminate\\Container\\Container',
      7 => 'Firefly\\Config\\Config',
      8 => 'Firefly\\Security\\Web\\RememberMe\\RememberMeServices',
    ),
  ),
  11 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Logout\\LogoutFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -93,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Web\\Settings\\LogoutSettings',
      1 => 'Firefly\\Security\\Web\\Logout\\LogoutHandler',
      2 => 'Firefly\\Security\\Web\\Csrf\\SessionCsrf',
      3 => 'Illuminate\\Container\\Container',
      4 => 'Firefly\\Config\\Config',
      5 => 'Firefly\\Security\\Web\\Logout\\LogoutSuccessHandler',
    ),
  ),
  12 => 
  array (
    'class' => 'Firefly\\Security\\Web\\Logout\\LogoutHandler',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 0,
    'qualifier' => NULL,
    'interfaces' => 
    array (
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Web\\Settings\\LogoutSettings',
      1 => 'Firefly\\Security\\Session\\SecurityContextRepository',
      2 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
      3 => 'Firefly\\Security\\Web\\RememberMe\\RememberMeServices',
    ),
  ),
  13 => 
  array (
    'class' => 'Firefly\\Security\\Web\\RememberMe\\RememberMeAuthenticationFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -83,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Security\\Session\\SecurityContextRepository',
      1 => 'Firefly\\Security\\Session\\SessionSecuritySettings',
      2 => 'Firefly\\Security\\Event\\AuthenticationEventPublisher',
      3 => 'Firefly\\Config\\Config',
      4 => 'Firefly\\Security\\Web\\RememberMe\\RememberMeServices',
    ),
  ),
  14 => 
  array (
    'class' => 'Firefly\\Security\\Web\\SecurityHeadersFilter',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -95,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Web\\Filter\\WebFilter',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Config\\Config',
    ),
  ),
);
