<?php

declare(strict_types=1);

namespace Firefly\Config\Scanner;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

final class ConfigManifestCompiler
{
    /**
     * @param  list<ConfigPropertiesDescriptor>  $properties
     */
    public function compile(array $properties): string
    {
        $rows = array_map(static fn (ConfigPropertiesDescriptor $d): array => $d->toArray(), $properties);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/config. Do not edit.\n\nreturn "
            .var_export($rows, true)
            .";\n";
    }

    /**
     * @param  list<ConfigPropertiesDescriptor>  $properties
     */
    public function write(array $properties, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($properties)) === false) {
            throw new ConfigurationException("Could not write config-properties manifest to {$path}.");
        }
    }
}
