<?php

declare(strict_types=1);

namespace Firefly\Security\Tests\Support;

use Firefly\Cqrs\CqrsServiceProvider;
use Firefly\Cqrs\CqrsWiringProvider;
use Firefly\OpenApi\OpenApiServiceProvider;
use Firefly\OpenApi\OpenApiWiringProvider;
use Firefly\Security\SecurityServiceProvider;
use Firefly\Security\SecurityWiringProvider;
use Firefly\Testing\FireflyTestCase;
use Firefly\Validation\ValidationServiceProvider;
use Firefly\Web\WebServiceProvider;

/**
 * THE SETUP THE METHOD-RULE CONTRIBUTOR EXISTS FOR, BOOTED WHOLE: firefly/openapi beside firefly/security,
 * URL rules that open EVERYTHING (`*` permitAll — Spring's `anyRequest().permitAll()` shape), and the
 * protection living entirely on the handlers as #[PreAuthorize]/#[PostAuthorize]. The document is fetched
 * over HTTP from the real `/openapi.json` route, generated by the container's own OpenApiGenerator bean out
 * of the container's own contributors, and the very manifest that decides what it SAYS about each path is
 * the manifest MethodSecurityControllerGuard is enforcing on the request that fetched it.
 *
 * WHY IT CANNOT LIVE IN packages/openapi, where the security capstone already is: that capstone boots
 * firefly/security but has no method-secured route and no authorization server, so neither this contributor
 * nor security-oauth2-server's scheme is ever exercised by it — and `deptrac.yaml` gives firefly/openapi no
 * edge to either package, so its fixtures can never carry a #[PreAuthorize]. The package that owns the
 * rules is the package that has to prove the document tells the truth about them.
 *
 * The rules are spelled with a leading slash, the RouteManifest's spelling, because that is what an
 * operator copying a URL writes; both sides agree only because HttpSecurity normalises every pattern where
 * it is built and ConfiguredSecurity mirrors it.
 */
abstract class MethodSecuredDocumentCapstoneTestCase extends FireflyTestCase
{
    protected function fireflyProviders(): array
    {
        return [
            ValidationServiceProvider::class,
            WebServiceProvider::class,
            OpenApiServiceProvider::class,
            OpenApiWiringProvider::class,
            CqrsServiceProvider::class,
            CqrsWiringProvider::class,
            SecurityServiceProvider::class,
            SecurityWiringProvider::class,
        ];
    }

    /** @return array<string, mixed> extra config keys, seeded before boot */
    protected function securityOverrides(): array
    {
        return [];
    }

    /** @return array<string, mixed> */
    protected function configOverrides(): array
    {
        return [
            'app.env' => 'testing',
            'app.debug' => false,
            'firefly.scan.paths' => ['Firefly\\Security\\Tests\\Fixtures\\OpenApiDoc\\' => dirname(__DIR__).'/Fixtures/OpenApiDoc'],
            'firefly.openapi.enabled' => true,
            'firefly.openapi.viewer.enabled' => false,
            'firefly.openapi.title' => 'Documented Orders API',
            'firefly.openapi.version' => '1.0.0',
            'firefly.security.enabled' => true,
            'firefly.security.jwt.enabled' => true,
            'firefly.security.jwt.secret' => str_repeat('s', 40),
            'firefly.security.http.enabled' => true,
            // Every path open at the URL layer. What refuses a caller here is the dispatcher, and nothing
            // but the compiled method-security manifest knows it.
            'firefly.security.http.rules' => [
                ['pattern' => '*', 'access' => 'permitAll'],
            ],
            ...$this->securityOverrides(),
        ];
    }

    /**
     * The served document, decoded — fetched over HTTP rather than generated in-process, so what is asserted
     * is the bytes a client gets.
     *
     * @return array<string, mixed>
     */
    public function document(): array
    {
        /** @var array<string, mixed> $document */
        $document = json_decode($this->responseBody($this->get('/openapi.json')->assertStatus(200)), true, flags: JSON_THROW_ON_ERROR);

        return $document;
    }

    /**
     * One operation of the served document.
     *
     * @return array<string, mixed>
     */
    public function operation(string $path, string $method = 'get'): array
    {
        /** @var array<string, array<string, array<string, mixed>>> $paths */
        $paths = $this->document()['paths'];

        return $paths[$path][$method];
    }

    /** @return array<string, list<string>> the scheme names every operation of the document refers to */
    public function namedSchemes(): array
    {
        $named = [];

        /** @var array<string, array<string, mixed>> $paths */
        $paths = $this->document()['paths'];
        foreach ($paths as $operations) {
            foreach ($operations as $operation) {
                if (! is_array($operation) || ! isset($operation['security']) || ! is_array($operation['security'])) {
                    continue;
                }
                /** @var list<array<string, list<string>>> $entries */
                $entries = $operation['security'];
                foreach ($entries as $entry) {
                    foreach ($entry as $scheme => $scopes) {
                        $named[$scheme] = $scopes;
                    }
                }
            }
        }

        return $named;
    }
}
