<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Actuator\\Health\\DbHealthIndicator',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.management.endpoint.health.db.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Actuator\\Introspection\\ScheduledTasksEndpoint',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnClass',
                'args' => [
                    0 => 'Firefly\\Scheduling\\Schedule\\ScheduledManifest',
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
];
