<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return array (
  0 => 
  array (
    'class' => 'Firefly\\Actuator\\Health\\DbHealthIndicator',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.management.endpoint.health.db.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
);
