<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Actuator\\Health\\DbHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
    ],
    1 => [
        'class' => 'Firefly\\Actuator\\Health\\DiskSpaceHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
    ],
    2 => [
        'class' => 'Firefly\\Actuator\\Health\\PingHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
    ],
    3 => [
        'class' => 'Firefly\\Actuator\\Info\\AppInfoContributor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Info\\InfoContributor',
        ],
        'beans' => [
        ],
        'lazy' => false,
    ],
    4 => [
        'class' => 'Firefly\\Actuator\\Info\\BuildInfoContributor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Info\\InfoContributor',
        ],
        'beans' => [
        ],
        'lazy' => false,
    ],
];
