<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Actuator\\ActuatorAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 1000,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'exposureModel',
                'returns' => 'Firefly\\Actuator\\Endpoint\\ExposureModel',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            1 => [
                'method' => 'managementServerSettings',
                'returns' => 'Firefly\\Actuator\\Server\\ManagementServerSettings',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            2 => [
                'method' => 'managementPortGuard',
                'returns' => 'Firefly\\Actuator\\Server\\ManagementPortGuard',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Actuator\\Server\\ManagementServerSettings',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Actuator\\Health\\DbHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Database\\ConnectionResolverInterface',
        ],
    ],
    2 => [
        'class' => 'Firefly\\Actuator\\Health\\DiskSpaceHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Config\\Config',
        ],
    ],
    3 => [
        'class' => 'Firefly\\Actuator\\Health\\HealthEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Actuator\\Health\\HealthContributorRegistry',
            1 => 'Firefly\\Actuator\\Health\\StatusAggregator',
            2 => 'Firefly\\Config\\Config',
        ],
    ],
    4 => [
        'class' => 'Firefly\\Actuator\\Health\\PingHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    5 => [
        'class' => 'Firefly\\Actuator\\Info\\AppInfoContributor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Info\\InfoContributor',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Config\\Config',
        ],
    ],
    6 => [
        'class' => 'Firefly\\Actuator\\Info\\BuildInfoContributor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Info\\InfoContributor',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Config\\Config',
        ],
    ],
    7 => [
        'class' => 'Firefly\\Actuator\\Info\\InfoEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Actuator\\Info\\InfoContributorRegistry',
        ],
    ],
    8 => [
        'class' => 'Firefly\\Actuator\\Info\\RuntimeInfoContributor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Info\\InfoContributor',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    9 => [
        'class' => 'Firefly\\Actuator\\Introspection\\BeansEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => true,
        'dependencies' => [
            0 => 'Firefly\\Actuator\\Introspection\\BeansCatalog',
        ],
    ],
    10 => [
        'class' => 'Firefly\\Actuator\\Introspection\\CachesEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Contracts\\Config\\Repository',
        ],
    ],
    11 => [
        'class' => 'Firefly\\Actuator\\Introspection\\ConditionsEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => true,
        'dependencies' => [
            0 => 'Firefly\\Context\\Condition\\ConditionEvaluationReport',
        ],
    ],
    12 => [
        'class' => 'Firefly\\Actuator\\Introspection\\ConfigPropsEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Contracts\\Container\\Container',
        ],
    ],
    13 => [
        'class' => 'Firefly\\Actuator\\Introspection\\EnvEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Contracts\\Config\\Repository',
        ],
    ],
    14 => [
        'class' => 'Firefly\\Actuator\\Introspection\\LoggersEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Log\\LogManager',
            1 => 'Illuminate\\Contracts\\Config\\Repository',
        ],
    ],
    15 => [
        'class' => 'Firefly\\Actuator\\Introspection\\MappingsEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Web\\Route\\RouteManifest',
        ],
    ],
    16 => [
        'class' => 'Firefly\\Actuator\\Introspection\\ScheduledTasksEndpoint',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Endpoint\\ActuatorEndpoint',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Scheduling\\Schedule\\ScheduledManifest',
        ],
    ],
];
