<?php

declare(strict_types=1);

namespace Lumen\Application\Command;

use Lumen\Domain\Currency;

/**
 * Command: open a new wallet for an owner in a given currency. A plain readonly DTO — the CQRS bus needs no marker
 * interface (per docs/modules/cqrs.md); the handler is resolved by the command's class-string. The wallet id is
 * generated by OpenWalletHandler and returned to the caller.
 */
final readonly class OpenWallet
{
    public function __construct(
        public string $ownerId,
        public Currency $currency,
    ) {}
}
