<?php

declare(strict_types=1);

namespace Firefly\OpenApi\Tests\Support;

/**
 * The secured openapi capstone with security actually TURNED ON: the master flag, the local JWT filter with
 * a secret long enough for JwtService to accept, HTTP Basic beside it, and URL rules that make one fixture
 * path public and the rest of them protected.
 *
 * TWO MECHANISMS, because one of them could never catch the failure that matters most here: a document
 * publishing a scheme no operation references. With `jwt` and `http_basic` both on the runtime really does
 * accept either credential, so the operation's `security` must be the two-entry OR-list, and the capstone
 * can assert the invariant directly — every published scheme is named by something, and everything named is
 * published.
 *
 * THE RULE PATTERNS ARE SPELLED WITH A LEADING SLASH ON PURPOSE. That is the spelling a RouteManifest path
 * uses and the one an operator copying a URL writes, and `$request->path()` never carries it — so the two
 * sides only agree because HttpSecurity normalises every pattern where it is built and ConfiguredSecurity
 * mirrors that normalisation. If either half of that stopped being true, these rules would go dead and every
 * test in this file would fetch a 401 instead of a document.
 *
 * This is the boot that proves the feature rather than the class: the document under test is fetched over
 * HTTP from the real `/openapi.json` route, generated by the container's own OpenApiGenerator bean, whose
 * SecurityModel the auto-configuration assembled out of the container's own contributors — and the very
 * rules that decide what the document SAYS about each path are the rules HttpSecurityFilter is enforcing on
 * the request that fetched it. A document that disagreed with the filter could not be produced here without
 * the disagreement being visible.
 *
 * `openapi.json` is the first rule for a reason a reader should not have to work out: with the master flag
 * and `http.enabled` both on, the rules are deny-by-default, and the spec route is an ordinary route like
 * any other. Without a permitAll for it, this capstone would be asserting against a 401.
 */
abstract class SecuredSchemesCapstoneTestCase extends SecuredOpenApiCapstoneTestCase
{
    protected function configOverrides(): array
    {
        return [
            ...parent::configOverrides(),
            'firefly.security.enabled' => true,
            'firefly.security.jwt.enabled' => true,
            'firefly.security.jwt.secret' => str_repeat('s', 40),
            'firefly.security.http_basic.enabled' => true,
            'firefly.security.http.enabled' => true,
            'firefly.security.http.rules' => [
                ['pattern' => '/openapi.json', 'access' => 'permitAll'],
                ['pattern' => '/openapi', 'access' => 'permitAll'],
                ['pattern' => '/openapi/*', 'access' => 'permitAll'],
                ['pattern' => '/api/orders', 'access' => 'permitAll'],
                ['pattern' => '/api/orders/*', 'access' => 'hasRole:ADMIN'],
                ['pattern' => '*', 'access' => 'authenticated'],
            ],
        ];
    }
}
