<?php

declare(strict_types=1);

namespace Firefly\OpenApi\Tests\Support;

/**
 * The secured openapi capstone with security actually TURNED ON: the master flag, the local JWT filter with
 * a secret long enough for JwtService to accept, and URL rules that make one fixture path public and the
 * rest of them protected.
 *
 * This is the boot that proves the feature rather than the class: the document under test is fetched over
 * HTTP from the real `/openapi.json` route, generated by the container's own OpenApiGenerator bean, whose
 * SecurityModel the auto-configuration assembled out of the container's own contributors — and the very
 * rules that decide what the document SAYS about each path are the rules HttpSecurityFilter is enforcing on
 * the request that fetched it. A document that disagreed with the filter could not be produced here without
 * the disagreement being visible.
 *
 * `openapi.json` is the first rule for a reason a reader should not have to work out: with the master flag
 * and `http.enabled` both on, the rules are deny-by-default, and the spec route is an ordinary route like
 * any other. Without a permitAll for it, this capstone would be asserting against a 401.
 */
abstract class SecuredSchemesCapstoneTestCase extends SecuredOpenApiCapstoneTestCase
{
    protected function configOverrides(): array
    {
        return [
            ...parent::configOverrides(),
            'firefly.security.enabled' => true,
            'firefly.security.jwt.enabled' => true,
            'firefly.security.jwt.secret' => str_repeat('s', 40),
            'firefly.security.http.enabled' => true,
            'firefly.security.http.rules' => [
                ['pattern' => 'openapi.json', 'access' => 'permitAll'],
                ['pattern' => 'openapi', 'access' => 'permitAll'],
                ['pattern' => 'openapi/*', 'access' => 'permitAll'],
                ['pattern' => 'api/orders', 'access' => 'permitAll'],
                ['pattern' => 'api/orders/*', 'access' => 'hasRole:ADMIN'],
                ['pattern' => '*', 'access' => 'authenticated'],
            ],
        ];
    }
}
