<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return array (
  0 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Boot\\FeatureFlagsLifecycle',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.feature-flags.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  1 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Context\\ApplicationEvaluationContextContributor',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.feature-flags.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  2 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluatorConfiguration',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
    ),
    'beanConditions' => 
    array (
      0 => 
      array (
        'method' => 'flagdEvaluator',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluator',
            ),
          ),
        ),
      ),
    ),
  ),
  3 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\FeatureFlagsAutoConfiguration',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
    ),
    'beanConditions' => 
    array (
      0 => 
      array (
        'method' => 'featureFlagsSettings',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
            ),
          ),
        ),
      ),
      1 => 
      array (
        'method' => 'featureFlagMetrics',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\FeatureFlags\\Telemetry\\FeatureFlagMetrics',
            ),
          ),
        ),
      ),
      2 => 
      array (
        'method' => 'flagRegistry',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'OpenFeature\\interfaces\\provider\\Provider',
            ),
          ),
          2 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\FeatureFlags\\Registry\\FlagRegistry',
            ),
          ),
        ),
      ),
      3 => 
      array (
        'method' => 'openFeatureProvider',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'OpenFeature\\interfaces\\provider\\Provider',
            ),
          ),
        ),
      ),
      4 => 
      array (
        'method' => 'evaluationContextResolver',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\FeatureFlags\\Context\\EvaluationContextResolver',
            ),
          ),
        ),
      ),
      5 => 
      array (
        'method' => 'featureFlags',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'Firefly\\FeatureFlags\\FeatureFlags',
            ),
          ),
        ),
      ),
      6 => 
      array (
        'method' => 'featureFlagsClient',
        'conditions' => 
        array (
          0 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
            'args' => 
            array (
              0 => 'firefly.feature-flags.enabled',
              1 => 'true',
              2 => false,
            ),
          ),
          1 => 
          array (
            'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
            'args' => 
            array (
              0 => 'OpenFeature\\interfaces\\flags\\Client',
            ),
          ),
        ),
      ),
    ),
  ),
  4 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Source\\ConfigFlagSource',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.feature-flags.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
      1 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
        'args' => 
        array (
          0 => 'OpenFeature\\interfaces\\provider\\Provider',
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
  5 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Source\\FileFlagSource',
    'postConstruct' => 
    array (
    ),
    'preDestroy' => 
    array (
    ),
    'listeners' => 
    array (
    ),
    'conditions' => 
    array (
      0 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.feature-flags.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
      1 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
        'args' => 
        array (
          0 => 'firefly.feature-flags.sources.file.enabled',
          1 => 'true',
          2 => false,
        ),
      ),
      2 => 
      array (
        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
        'args' => 
        array (
          0 => 'OpenFeature\\interfaces\\provider\\Provider',
        ),
      ),
    ),
    'beanConditions' => 
    array (
    ),
  ),
);
