<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\FeatureFlags\\Boot\\FeatureFlagsLifecycle',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.feature-flags.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\FeatureFlags\\Context\\ApplicationEvaluationContextContributor',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.feature-flags.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    2 => [
        'class' => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluatorConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'flagdEvaluator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluator',
                        ],
                    ],
                ],
            ],
        ],
    ],
    3 => [
        'class' => 'Firefly\\FeatureFlags\\FeatureFlagsAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'featureFlagsSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'featureFlagMetrics',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Telemetry\\FeatureFlagMetrics',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'flagRegistry',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'OpenFeature\\interfaces\\provider\\Provider',
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Registry\\FlagRegistry',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'openFeatureProvider',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'OpenFeature\\interfaces\\provider\\Provider',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'evaluationContextResolver',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Context\\EvaluationContextResolver',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'featureFlags',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\FeatureFlags',
                        ],
                    ],
                ],
            ],
            6 => [
                'method' => 'featureFlagsClient',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.feature-flags.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'OpenFeature\\interfaces\\flags\\Client',
                        ],
                    ],
                ],
            ],
        ],
    ],
    4 => [
        'class' => 'Firefly\\FeatureFlags\\Gating\\FeatureFlagsGatingConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'featureFlagGate',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Gating\\FeatureFlagGate',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'routeGateDecisions',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Gating\\RouteGateDecisions',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'featureFlagMethodInterceptor',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\FeatureFlags\\Gating\\FeatureFlagMethodInterceptor',
                        ],
                    ],
                ],
            ],
        ],
    ],
    5 => [
        'class' => 'Firefly\\FeatureFlags\\Source\\ConfigFlagSource',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.feature-flags.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            1 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                'args' => [
                    0 => 'OpenFeature\\interfaces\\provider\\Provider',
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    6 => [
        'class' => 'Firefly\\FeatureFlags\\Source\\FileFlagSource',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.feature-flags.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            1 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.feature-flags.sources.file.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            2 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                'args' => [
                    0 => 'OpenFeature\\interfaces\\provider\\Provider',
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
];
