<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\FeatureFlags\\Context\\ApplicationEvaluationContextContributor',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -200,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\FeatureFlags\\Context\\EvaluationContextContributor',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Contracts\\Config\\Repository',
        ],
    ],
    1 => [
        'class' => 'Firefly\\FeatureFlags\\FeatureFlagsAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 700,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'featureFlagsSettings',
                'returns' => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    2 => [
        'class' => 'Firefly\\FeatureFlags\\Source\\ConfigFlagSource',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\FeatureFlags\\Source\\FlagSource',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
        ],
    ],
    3 => [
        'class' => 'Firefly\\FeatureFlags\\Source\\FileFlagSource',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\FeatureFlags\\Source\\FlagSource',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
        ],
    ],
];
