<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return array (
  0 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Boot\\FeatureFlagsLifecycle',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 0,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\Kernel\\Lifecycle',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\Container\\Container',
      1 => 'OpenFeature\\interfaces\\flags\\API',
    ),
  ),
  1 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Context\\ApplicationEvaluationContextContributor',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => -200,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\FeatureFlags\\Context\\EvaluationContextContributor',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Illuminate\\Contracts\\Config\\Repository',
    ),
  ),
  2 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluatorConfiguration',
    'stereotype' => 'configuration',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 700,
    'qualifier' => NULL,
    'interfaces' => 
    array (
    ),
    'beans' => 
    array (
      0 => 
      array (
        'method' => 'flagdEvaluator',
        'returns' => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluator',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
    ),
    'lazy' => false,
    'dependencies' => 
    array (
    ),
  ),
  3 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\FeatureFlagsAutoConfiguration',
    'stereotype' => 'configuration',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 700,
    'qualifier' => NULL,
    'interfaces' => 
    array (
    ),
    'beans' => 
    array (
      0 => 
      array (
        'method' => 'featureFlagsSettings',
        'returns' => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Config\\Config',
        ),
      ),
      1 => 
      array (
        'method' => 'featureFlagMetrics',
        'returns' => 'Firefly\\FeatureFlags\\Telemetry\\FeatureFlagMetrics',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
        ),
      ),
      2 => 
      array (
        'method' => 'flagRegistry',
        'returns' => 'Firefly\\FeatureFlags\\Registry\\FlagRegistry',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Container\\Container',
          1 => 'Illuminate\\Contracts\\Cache\\Repository',
          2 => 'Firefly\\Context\\Event\\ApplicationEventPublisher',
          3 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
      3 => 
      array (
        'method' => 'openFeatureProvider',
        'returns' => 'OpenFeature\\interfaces\\provider\\Provider',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\FeatureFlags\\Registry\\FlagRegistry',
          1 => 'Firefly\\FeatureFlags\\Evaluation\\FlagdEvaluator',
          2 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
      4 => 
      array (
        'method' => 'evaluationContextResolver',
        'returns' => 'Firefly\\FeatureFlags\\Context\\EvaluationContextResolver',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\Container\\Container',
          1 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
      5 => 
      array (
        'method' => 'featureFlags',
        'returns' => 'Firefly\\FeatureFlags\\FeatureFlags',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'OpenFeature\\interfaces\\provider\\Provider',
          1 => 'Firefly\\FeatureFlags\\Context\\EvaluationContextResolver',
          2 => 'Firefly\\FeatureFlags\\Telemetry\\FeatureFlagMetrics',
          3 => 'Firefly\\Context\\Event\\ApplicationEventPublisher',
          4 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
          5 => 'Firefly\\Container\\Container',
          6 => 'Psr\\Log\\LoggerInterface',
        ),
      ),
      6 => 
      array (
        'method' => 'featureFlagsClient',
        'returns' => 'OpenFeature\\interfaces\\flags\\Client',
        'name' => NULL,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'lazy' => false,
        'dependencies' => 
        array (
          0 => 'Firefly\\FeatureFlags\\FeatureFlags',
        ),
      ),
    ),
    'lazy' => false,
    'dependencies' => 
    array (
    ),
  ),
  4 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Source\\ConfigFlagSource',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 0,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\FeatureFlags\\Source\\FlagSource',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
    ),
  ),
  5 => 
  array (
    'class' => 'Firefly\\FeatureFlags\\Source\\FileFlagSource',
    'stereotype' => 'component',
    'name' => NULL,
    'scope' => 'Singleton',
    'primary' => false,
    'order' => 0,
    'qualifier' => NULL,
    'interfaces' => 
    array (
      0 => 'Firefly\\FeatureFlags\\Source\\FlagSource',
    ),
    'beans' => 
    array (
    ),
    'lazy' => false,
    'dependencies' => 
    array (
      0 => 'Firefly\\FeatureFlags\\FeatureFlagsSettings',
    ),
  ),
);
