<?php

declare(strict_types=1);

namespace Firefly\Security\Access\Method;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/** var_export of the method-security rows into a require-able file. Run Pint after any regen. */
final class SecurityMethodManifestCompiler
{
    /**
     * @param  list<SecurityMethodDescriptor>  $rules
     */
    public function compile(array $rules): string
    {
        $rows = array_map(static fn (SecurityMethodDescriptor $r): array => $r->toArray(), $rules);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/security. Do not edit.\n\nreturn "
            .var_export($rows, true)
            .";\n";
    }

    /**
     * @param  list<SecurityMethodDescriptor>  $rules
     */
    public function write(array $rules, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($rules)) === false) {
            throw new ConfigurationException("Could not write security method manifest to {$path}.");
        }
    }
}
