<?php

declare(strict_types=1);

namespace Firefly\Scheduling\Schedule;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/**
 * Mirrors the web RouteManifestCompiler: var_export of ScheduledDescriptor rows into a require-able PHP file.
 *
 * @phpstan-import-type ScheduledRow from ScheduledDescriptor
 */
final class ScheduledManifestCompiler
{
    /**
     * @param  list<ScheduledDescriptor>  $tasks
     */
    public function compile(array $tasks): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/scheduling. Do not edit.\n\nreturn "
            .var_export($this->toArray($tasks), true)
            .";\n";
    }

    /**
     * @param  list<ScheduledDescriptor>  $tasks
     * @return list<ScheduledRow>
     */
    public function toArray(array $tasks): array
    {
        return array_map(static fn (ScheduledDescriptor $task): array => $task->toArray(), $tasks);
    }

    /**
     * @param  list<ScheduledDescriptor>  $tasks
     */
    public function write(array $tasks, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($tasks)) === false) {
            throw new ConfigurationException("Could not write scheduled manifest to {$path}.");
        }
    }
}
