<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Eda\\Rabbitmq\\RabbitMqAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 900,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'rabbitConnectionFactory',
                'returns' => 'Firefly\\Eda\\Rabbitmq\\RabbitMqConnectionFactory',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            1 => [
                'method' => 'connectionOpener',
                'returns' => 'Firefly\\Eda\\Rabbitmq\\OpensConnection',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            2 => [
                'method' => 'subscriberRegistry',
                'returns' => 'Firefly\\Eda\\Bus\\SubscriberRegistry',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
            3 => [
                'method' => 'eventPublisher',
                'returns' => 'Firefly\\Eda\\EventPublisher',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
            ],
        ],
        'lazy' => false,
    ],
    1 => [
        'class' => 'Firefly\\Eda\\Rabbitmq\\RabbitMqHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
    ],
];
