<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Eda\\Rabbitmq\\RabbitMqAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'subscriberRegistry',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'rabbitmq',
                            2 => false,
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'eventPublisher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'rabbitmq',
                            2 => false,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
