<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 600,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'oauth2ClientSettings',
                'returns' => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            1 => [
                'method' => 'oidcDiscovery',
                'returns' => 'Firefly\\Security\\OAuth2\\Client\\Discovery\\OidcDiscovery',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Illuminate\\Contracts\\Container\\Container',
                    1 => 'Illuminate\\Contracts\\Cache\\Repository',
                    2 => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
                ],
            ],
            2 => [
                'method' => 'clientRegistrationRepository',
                'returns' => 'Firefly\\Security\\OAuth2\\Client\\Registration\\ClientRegistrationRepository',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                    1 => 'Firefly\\Security\\OAuth2\\Client\\Discovery\\OidcDiscovery',
                    2 => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
                ],
            ],
            3 => [
                'method' => 'oauth2AuthorizationRequestResolver',
                'returns' => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestResolver',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            4 => [
                'method' => 'authorizationRequestRepository',
                'returns' => 'Firefly\\Security\\OAuth2\\Client\\Web\\AuthorizationRequestRepository',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            5 => [
                'method' => 'loginPageLinks',
                'returns' => 'Firefly\\Security\\Web\\Login\\LoginPageLinks',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Client\\Registration\\ClientRegistrationRepository',
                    1 => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
                    2 => 'Psr\\Log\\LoggerInterface',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestRedirectFilter',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => -89,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Web\\Filter\\WebFilter',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Security\\OAuth2\\Client\\Registration\\ClientRegistrationRepository',
            1 => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestResolver',
            2 => 'Firefly\\Security\\OAuth2\\Client\\Web\\AuthorizationRequestRepository',
            3 => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
            4 => 'Illuminate\\Container\\Container',
            5 => 'Firefly\\Config\\Config',
        ],
    ],
];
