<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'oauth2ClientSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'oidcDiscovery',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Discovery\\OidcDiscovery',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'clientRegistrationRepository',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Registration\\ClientRegistrationRepository',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'oauth2AccessTokenResponseClient',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Token\\OAuth2AccessTokenResponseClient',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'oidcIdTokenDecoderFactory',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Oidc\\OidcIdTokenDecoderFactory',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'oauth2AuthorizedClientService',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Authorized\\OAuth2AuthorizedClientService',
                        ],
                    ],
                ],
            ],
            6 => [
                'method' => 'oauth2AuthorizedClientRepository',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Authorized\\OAuth2AuthorizedClientRepository',
                        ],
                    ],
                ],
            ],
            7 => [
                'method' => 'oauth2AuthorizationRequestResolver',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestResolver',
                        ],
                    ],
                ],
            ],
            8 => [
                'method' => 'authorizationRequestRepository',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Web\\AuthorizationRequestRepository',
                        ],
                    ],
                ],
            ],
            9 => [
                'method' => 'loginPageLinks',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Login\\LoginPageLinks',
                        ],
                    ],
                ],
            ],
            10 => [
                'method' => 'logoutSuccessHandler',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.logout.oidc_initiated',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    3 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Logout\\LogoutSuccessHandler',
                        ],
                    ],
                ],
            ],
            11 => [
                'method' => 'userInfoClient',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\User\\UserInfoClient',
                        ],
                    ],
                ],
            ],
            12 => [
                'method' => 'oauth2UserService',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\User\\OAuth2UserService',
                        ],
                    ],
                ],
            ],
            13 => [
                'method' => 'oidcUserService',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\User\\OidcUserService',
                        ],
                    ],
                ],
            ],
            14 => [
                'method' => 'oauth2LoginAuthenticationProvider',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Web\\Login\\OAuth2LoginAuthenticationProvider',
                        ],
                    ],
                ],
            ],
        ],
    ],
    1 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestRedirectFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            1 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.client.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            2 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.client.login.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    2 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2LoginAuthenticationFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            1 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.client.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            2 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.client.login.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
];
