<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'oauth2ClientSettings',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\OAuth2ClientSettings',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'oidcDiscovery',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Discovery\\OidcDiscovery',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'clientRegistrationRepository',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Registration\\ClientRegistrationRepository',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'oauth2AuthorizationRequestResolver',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestResolver',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'authorizationRequestRepository',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\OAuth2\\Client\\Web\\AuthorizationRequestRepository',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'loginPageLinks',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    1 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.security.oauth2.client.login.enabled',
                            1 => 'true',
                            2 => false,
                        ],
                    ],
                    2 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Security\\Web\\Login\\LoginPageLinks',
                        ],
                    ],
                ],
            ],
        ],
    ],
    1 => [
        'class' => 'Firefly\\Security\\OAuth2\\Client\\Web\\OAuth2AuthorizationRequestRedirectFilter',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            1 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.client.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
            2 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.security.oauth2.client.login.enabled',
                    1 => 'true',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
];
