<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Scheduling\\Postgres\\PgAdvisoryLockAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'distributedLock',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.scheduling.lock.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
