<?php

declare(strict_types=1);

namespace Firefly\Web\Route;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/** Mirrors M2's ManifestCompiler: var_export of RouteDescriptor rows into a require-able PHP file. */
final class RouteManifestCompiler
{
    /**
     * @param  list<RouteDescriptor>  $routes
     */
    public function compile(array $routes): string
    {
        $rows = array_map(static fn (RouteDescriptor $r): array => $r->toArray(), $routes);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/web. Do not edit.\n\nreturn "
            .var_export($rows, true)
            .";\n";
    }

    /**
     * @param  list<RouteDescriptor>  $routes
     */
    public function write(array $routes, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($routes)) === false) {
            throw new ConfigurationException("Could not write route manifest to {$path}.");
        }
    }
}
