<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Security\\OAuth2\\Server\\Authorization\\OAuth2AuthorizationPurgeTask',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Firefly\\Security\\OAuth2\\Server\\Authorization\\OAuth2AuthorizationService',
            1 => 'Psr\\Log\\LoggerInterface',
        ],
    ],
    1 => [
        'class' => 'Firefly\\Security\\OAuth2\\Server\\OAuth2ServerAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 600,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'authorizationServerSettings',
                'returns' => 'Firefly\\Security\\OAuth2\\Server\\Settings\\AuthorizationServerSettings',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                ],
            ],
            1 => [
                'method' => 'jwtSigningKeys',
                'returns' => 'Firefly\\Security\\OAuth2\\Server\\Jose\\JwtSigningKeys',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Server\\Settings\\AuthorizationServerSettings',
                ],
            ],
            2 => [
                'method' => 'jwtGenerator',
                'returns' => 'Firefly\\Security\\OAuth2\\Server\\Jose\\JwtGenerator',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Server\\Jose\\JwtSigningKeys',
                ],
            ],
            3 => [
                'method' => 'oauth2JwksDocumentSource',
                'returns' => 'Firefly\\Security\\OAuth2\\JwksDocumentSource',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Server\\Jose\\JwtSigningKeys',
                ],
            ],
            4 => [
                'method' => 'registeredClientRepository',
                'returns' => 'Firefly\\Security\\OAuth2\\Server\\Client\\RegisteredClientRepository',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Server\\Settings\\AuthorizationServerSettings',
                    1 => 'Firefly\\Config\\Config',
                ],
            ],
            5 => [
                'method' => 'oauth2AuthorizationService',
                'returns' => 'Firefly\\Security\\OAuth2\\Server\\Authorization\\OAuth2AuthorizationService',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Server\\Settings\\AuthorizationServerSettings',
                ],
            ],
            6 => [
                'method' => 'oauth2AuthorizationConsentService',
                'returns' => 'Firefly\\Security\\OAuth2\\Server\\Authorization\\OAuth2AuthorizationConsentService',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Security\\OAuth2\\Server\\Settings\\AuthorizationServerSettings',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
];
