<?php

declare(strict_types=1);

namespace Firefly\Cqrs\Handler;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/**
 * Mirrors the ScheduledManifestCompiler: var_export of the handler rows + the destinations map into a require-able
 * PHP file with two top-level keys. Run Pint after any regen (the compiler emits raw var_export style).
 *
 * @phpstan-import-type HandlerRow from HandlerDescriptor
 */
final class HandlerManifestCompiler
{
    /**
     * @param  list<HandlerDescriptor>  $handlers
     * @param  array<string,string>  $destinations
     */
    public function compile(array $handlers, array $destinations): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/cqrs. Do not edit.\n\nreturn "
            .var_export($this->toArray($handlers, $destinations), true)
            .";\n";
    }

    /**
     * @param  list<HandlerDescriptor>  $handlers
     * @param  array<string,string>  $destinations
     * @return array{handlers: list<HandlerRow>, destinations: array<string,string>}
     */
    public function toArray(array $handlers, array $destinations): array
    {
        return [
            'handlers' => array_map(static fn (HandlerDescriptor $h): array => $h->toArray(), $handlers),
            'destinations' => $destinations,
        ];
    }

    /**
     * @param  list<HandlerDescriptor>  $handlers
     * @param  array<string,string>  $destinations
     */
    public function write(array $handlers, array $destinations, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($handlers, $destinations)) === false) {
            throw new ConfigurationException("Could not write handler manifest to {$path}.");
        }
    }
}
