<?php

declare(strict_types=1);

namespace Firefly\Data\Proxy;

use RuntimeException;

/**
 * Emits `final class {Short}__FireflyTransactionalProxy extends \{Target}` source in the target's namespace,
 * overriding each planned method with a MethodInvocation over the ORDERED interceptors the method's advice
 * names (`[$this->__fireflySecurityInterceptor, $this->__fireflyTxInterceptor]`), the descriptors baked as
 * literals keyed by their class, and the terminal `fn (array $__fireflyArgs) => parent::m(...$__fireflyArgs)`
 * (no `return` for void/never). One private, port-typed interceptor property and one private static
 * descriptor factory are declared PER ADVICE KIND the class uses (`__fireflyTxInterceptor` /
 * `__fireflyTxDescriptor('m')` for the transactional advice — the names a proxy has always had), plus a
 * public static `__fireflyAdvice()` table the ProxyFactory reads to know which interceptor to set where.
 * Signatures come from the scanner-rendered ProxyMethod strings, so this file is REFLECTION-FREE (the
 * sanctioned substrings live only in TransactionalScanner). The proxy declares NO constructor (the
 * ProxyFactory instantiates it via newInstanceWithoutConstructor). Generated classes are app artifacts
 * (firefly:cache, M15); load() writes + requires them for tests.
 *
 * Known-latent signature edges (rare; the scanner renders `self`/`static`/`never` correctly): a method declared
 * with a `: parent` return type resolves `parent` against the PROXY's parent (the target class) rather than the
 * target's own parent, so it may bind to the wrong class; likewise a parameter default that references a
 * cross-namespace class constant (e.g. `= OtherNs\Thing::CONST`) is rendered verbatim and may not resolve in the
 * generated proxy's namespace. Wrap the value or use a fully-qualified constant if you hit these. By-reference
 * parameters are rejected outright at scan time (see UnsupportedTransactionalMethodException).
 */
final class ProxyClassGenerator
{
    /**
     * Per-process private directory for materialised proxy sources — created once, lazily, with an unpredictable
     * name and 0700 permissions (see proxyDir()). Static so repeated load() calls in one process share it.
     */
    private static ?string $proxyDir = null;

    /**
     * @param  array<string, ProxyMethod>  $methods
     */
    public function generate(string $targetClass, array $methods): string
    {
        $namespace = $this->namespaceOf($targetClass);
        $shortName = $this->shortNameOf($targetClass);
        $proxyShort = $shortName.ProxyPlan::PROXY_SUFFIX;
        $advice = $this->adviceKinds($methods);

        $properties = '';
        foreach ($advice as $kind) {
            $properties .= '    private \\'.MethodInterceptor::class." \${$kind->property()};\n";
        }

        $overrides = '';
        foreach ($methods as $method) {
            $overrides .= $this->renderOverride($targetClass, $method);
        }

        $factories = '';
        foreach ($advice as $kind) {
            $factories .= $this->renderDescriptorFactory($kind, $methods);
        }

        $header = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/data. Do not edit.\n\n";
        $header .= $namespace === '' ? '' : "namespace {$namespace};\n\n";

        return $header
            ."final class {$proxyShort} extends \\{$targetClass}\n"
            ."{\n"
            .$properties
            ."\n"
            .$overrides
            .$factories
            .$this->renderAdviceTable($advice)
            ."}\n";
    }

    /**
     * @param  array<string, ProxyMethod>  $methods
     * @return class-string
     */
    public function load(string $targetClass, array $methods): string
    {
        /** @var class-string $proxyClass */
        $proxyClass = $targetClass.ProxyPlan::PROXY_SUFFIX;

        if (class_exists($proxyClass, false)) {
            return $proxyClass;
        }

        $file = $this->proxyDir().'/'.str_replace('\\', '_', $targetClass).'.php';

        // Open with 'x' (O_CREAT|O_EXCL): the create fails rather than following a symlink or reusing a
        // pre-existing file, closing the classic shared-/tmp symlink + write/require TOCTOU vector. Combined
        // with the private 0700 per-process directory below, an attacker has neither a predictable path to
        // pre-seat nor write access to the directory. We only ever require a file we just created here.
        $handle = fopen($file, 'xb');
        if ($handle === false) {
            throw new RuntimeException("Could not safely create transactional proxy file [{$file}].");
        }
        $source = $this->generate($targetClass, $methods);
        // Fail loud on a short/failed write rather than require() a truncated proxy that would fatal on load.
        if (fwrite($handle, $source) !== strlen($source) || ! fclose($handle)) {
            throw new RuntimeException("Could not fully write transactional proxy file [{$file}].");
        }
        require $file;

        return $proxyClass;
    }

    /**
     * The private, unpredictable, owner-only directory generated proxy sources are written to. A random suffix
     * means the path cannot be pre-created by another user, and 0700 means only this process's user can read or
     * write inside it. Created once per process and reused.
     */
    private function proxyDir(): string
    {
        if (self::$proxyDir !== null) {
            return self::$proxyDir;
        }

        $dir = sys_get_temp_dir().'/firefly-transactional-proxies-'.bin2hex(random_bytes(8));
        if (! mkdir($dir, 0o700, true) && ! is_dir($dir)) {
            throw new RuntimeException("Could not create private transactional proxy directory [{$dir}].");
        }

        return self::$proxyDir = $dir;
    }

    /**
     * Every advice kind any method of the class runs, in chain order.
     *
     * @param  array<string, ProxyMethod>  $methods
     * @return array<string, Advice>
     */
    private function adviceKinds(array $methods): array
    {
        $kinds = [];
        foreach ($methods as $method) {
            foreach ($method->advice as $bound) {
                $kinds[$bound->advice->id] = $bound->advice;
            }
        }
        uasort($kinds, static fn (Advice $a, Advice $b): int => $a->order <=> $b->order ?: strcmp($a->id, $b->id));

        return $kinds;
    }

    private function renderOverride(string $targetClass, ProxyMethod $method): string
    {
        $interceptors = [];
        $descriptors = [];
        foreach ($method->advice as $bound) {
            $interceptors[] = "\$this->{$bound->advice->property()}";
            $descriptors[] = '\\'.$bound->advice->descriptorClass."::class => self::{$bound->advice->factory()}('{$method->name}')";
        }

        $arguments = $method->argSource === '' ? '[]' : "[{$method->argSource}]";
        $call = '(new \\'.MethodInvocation::class."(\n"
            ."            \$this,\n"
            ."            \\{$targetClass}::class,\n"
            ."            '{$method->name}',\n"
            ."            {$arguments},\n"
            .'            ['.implode(', ', $interceptors)."],\n"
            .'            ['.implode(', ', $descriptors)."],\n"
            ."            fn (array \$__fireflyArgs) => parent::{$method->name}(...\$__fireflyArgs),\n"
            .'        ))->proceed()';

        $isVoid = in_array(ltrim($method->returnType, ': '), ['void', 'never'], true);
        $body = $isVoid ? "        {$call};\n" : "        return {$call};\n";

        return "    public function {$method->name}({$method->paramSource}){$method->returnType}\n"
            ."    {\n"
            .$body
            ."    }\n\n";
    }

    /**
     * @param  array<string, ProxyMethod>  $methods
     */
    private function renderDescriptorFactory(Advice $kind, array $methods): string
    {
        $type = '\\'.$kind->descriptorClass;
        $arms = '';
        foreach ($methods as $method) {
            foreach ($method->advice as $bound) {
                if ($bound->advice->id === $kind->id) {
                    $arms .= "            '{$method->name}' => {$bound->literal},\n";
                }
            }
        }

        // The transactional advice keeps its historical default (a REQUIRED descriptor); any other advice
        // has no meaningful default and a miss is a generator bug, so it fails loud.
        $default = $kind->id === Advice::TRANSACTIONAL
            ? "new {$type}"
            : "throw new \\LogicException('No {$kind->id} descriptor was compiled for method [' . \$method . '].')";

        return "    private static function {$kind->factory()}(string \$method): {$type}\n"
            ."    {\n"
            ."        return match (\$method) {\n"
            .$arms
            ."            default => {$default},\n"
            ."        };\n"
            ."    }\n\n";
    }

    /**
     * @param  array<string, Advice>  $advice
     */
    private function renderAdviceTable(array $advice): string
    {
        $rows = '';
        foreach ($advice as $kind) {
            $rows .= "            '{$kind->id}' => \\{$kind->interceptorClass}::class,\n";
        }

        return "    /**\n     * @return array<string, class-string<\\".MethodInterceptor::class.">> advice id => the interceptor bean the ProxyFactory sets\n     */\n"
            ."    public static function __fireflyAdvice(): array\n"
            ."    {\n"
            ."        return [\n"
            .$rows
            ."        ];\n"
            ."    }\n";
    }

    private function namespaceOf(string $class): string
    {
        $pos = strrpos($class, '\\');

        return $pos === false ? '' : substr($class, 0, $pos);
    }

    private function shortNameOf(string $class): string
    {
        $pos = strrpos($class, '\\');

        return $pos === false ? $class : substr($class, $pos + 1);
    }
}
