<?php

declare(strict_types=1);

namespace Firefly\Data\Proxy;

use Firefly\Data\Transaction\Isolation;
use Firefly\Data\Transaction\Propagation;
use Firefly\Data\Transaction\TransactionalDescriptor;
use Firefly\Data\Transaction\TransactionInterceptor;

/**
 * Emits `final class {Short}__FireflyTransactionalProxy extends \{Target}` source in the target's namespace,
 * overriding each transactional method with `return $this->__fireflyTxInterceptor->run(fn () =>
 * parent::m(...$args), self::__fireflyTxDescriptor('m'))` (no `return` for void/never). Signatures come from the
 * scanner-rendered ProxyMethod strings, so this file is REFLECTION-FREE (the sanctioned substrings live only in
 * TransactionalScanner). The proxy declares one private TransactionInterceptor property and a private static
 * __fireflyTxDescriptor() built from baked-in literals; it declares NO constructor (the ProxyFactory instantiates
 * it via newInstanceWithoutConstructor). Generated classes are app artifacts (firefly:cache, M15); load() writes
 * + requires them for tests.
 *
 * Known-latent signature edges (rare; the scanner renders `self`/`static`/`never` correctly): a method declared
 * with a `: parent` return type resolves `parent` against the PROXY's parent (the target class) rather than the
 * target's own parent, so it may bind to the wrong class; likewise a parameter default that references a
 * cross-namespace class constant (e.g. `= OtherNs\Thing::CONST`) is rendered verbatim and may not resolve in the
 * generated proxy's namespace. Wrap the value or use a fully-qualified constant if you hit these. By-reference
 * parameters are rejected outright at scan time (see UnsupportedTransactionalMethodException).
 */
final class ProxyClassGenerator
{
    /**
     * @param  array<string, ProxyMethod>  $methods
     */
    public function generate(string $targetClass, array $methods): string
    {
        $namespace = $this->namespaceOf($targetClass);
        $shortName = $this->shortNameOf($targetClass);
        $proxyShort = $shortName.'__FireflyTransactionalProxy';

        $interceptorType = '\\'.TransactionInterceptor::class;
        $descriptorType = '\\'.TransactionalDescriptor::class;

        $overrides = '';
        foreach ($methods as $method) {
            $overrides .= $this->renderOverride($method);
        }

        $descriptorSwitch = $this->renderDescriptorFactory($methods, $descriptorType);

        $header = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/data. Do not edit.\n\n";
        $header .= $namespace === '' ? '' : "namespace {$namespace};\n\n";

        return $header
            ."final class {$proxyShort} extends \\{$targetClass}\n"
            ."{\n"
            ."    private {$interceptorType} \$__fireflyTxInterceptor;\n\n"
            .$overrides
            .$descriptorSwitch
            ."}\n";
    }

    /**
     * @param  array<string, ProxyMethod>  $methods
     * @return class-string
     */
    public function load(string $targetClass, array $methods): string
    {
        /** @var class-string $proxyClass */
        $proxyClass = $targetClass.'__FireflyTransactionalProxy';

        if (class_exists($proxyClass, false)) {
            return $proxyClass;
        }

        $dir = sys_get_temp_dir().'/firefly-transactional-proxies';
        if (! is_dir($dir)) {
            mkdir($dir, 0o775, true);
        }

        $file = $dir.'/'.str_replace('\\', '_', $targetClass).'.php';
        file_put_contents($file, $this->generate($targetClass, $methods));
        require $file;

        return $proxyClass;
    }

    private function renderOverride(ProxyMethod $method): string
    {
        $proceed = "fn () => parent::{$method->name}({$method->argSource})";
        $call = "\$this->__fireflyTxInterceptor->run(\n            {$proceed},\n            self::__fireflyTxDescriptor('{$method->name}'),\n        )";

        $isVoid = in_array(ltrim($method->returnType, ': '), ['void', 'never'], true);
        $body = $isVoid ? "        {$call};\n" : "        return {$call};\n";

        return "    public function {$method->name}({$method->paramSource}){$method->returnType}\n"
            ."    {\n"
            .$body
            ."    }\n\n";
    }

    /**
     * @param  array<string, ProxyMethod>  $methods
     */
    private function renderDescriptorFactory(array $methods, string $descriptorType): string
    {
        $arms = '';
        foreach ($methods as $method) {
            $arms .= "            '{$method->name}' => {$this->renderDescriptorLiteral($method->descriptor)},\n";
        }

        return "    private static function __fireflyTxDescriptor(string \$method): {$descriptorType}\n"
            ."    {\n"
            ."        return match (\$method) {\n"
            .$arms
            ."            default => new {$descriptorType},\n"
            ."        };\n"
            ."    }\n";
    }

    private function renderDescriptorLiteral(TransactionalDescriptor $descriptor): string
    {
        $propagation = '\\'.Propagation::class.'::'.$descriptor->propagation->name;
        $isolation = '\\'.Isolation::class.'::'.$descriptor->isolation->name;

        return 'new \\'.TransactionalDescriptor::class.'('
            ."propagation: {$propagation}, "
            ."isolation: {$isolation}, "
            .'readOnly: '.($descriptor->readOnly ? 'true' : 'false').', '
            .'rollbackFor: '.$this->exportClassList($descriptor->rollbackFor).', '
            .'noRollbackFor: '.$this->exportClassList($descriptor->noRollbackFor).', '
            .'connection: '.($descriptor->connection === null ? 'null' : var_export($descriptor->connection, true)).', '
            .'timeout: '.($descriptor->timeout === null ? 'null' : (string) $descriptor->timeout)
            .')';
    }

    /**
     * @param  list<class-string<\Throwable>>  $classes
     */
    private function exportClassList(array $classes): string
    {
        $items = array_map(static fn (string $class): string => var_export($class, true), $classes);

        return '['.implode(', ', $items).']';
    }

    private function namespaceOf(string $class): string
    {
        $pos = strrpos($class, '\\');

        return $pos === false ? '' : substr($class, 0, $pos);
    }

    private function shortNameOf(string $class): string
    {
        $pos = strrpos($class, '\\');

        return $pos === false ? $class : substr($class, $pos + 1);
    }
}
