<?php

declare(strict_types=1);

namespace Firefly\Data\Proxy;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/** var_export of the ProxyPlan into a require-able file — the TransactionalManifestCompiler idiom. */
final class ProxyPlanCompiler
{
    public function compile(ProxyPlan $plan): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/data. Do not edit.\n\nreturn "
            .var_export($plan->toArray(), true)
            .";\n";
    }

    public function write(ProxyPlan $plan, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($plan)) === false) {
            throw new ConfigurationException("Could not write proxy plan to {$path}.");
        }
    }
}
