<?php

declare(strict_types=1);

namespace Firefly\Messaging\Listener;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

/**
 * Mirrors EventListenerManifestCompiler: var_export of MessageListenerDescriptor rows into a require-able PHP file.
 *
 * @phpstan-import-type MessageListenerRow from MessageListenerDescriptor
 */
final class MessageListenerManifestCompiler
{
    /**
     * @param  list<MessageListenerDescriptor>  $listeners
     */
    public function compile(array $listeners): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/messaging. Do not edit.\n\nreturn "
            .var_export($this->toArray($listeners), true)
            .";\n";
    }

    /**
     * @param  list<MessageListenerDescriptor>  $listeners
     * @return list<MessageListenerRow>
     */
    public function toArray(array $listeners): array
    {
        return array_map(static fn (MessageListenerDescriptor $l): array => $l->toArray(), $listeners);
    }

    /**
     * @param  list<MessageListenerDescriptor>  $listeners
     */
    public function write(array $listeners, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($listeners)) === false) {
            throw new ConfigurationException("Could not write message-listener manifest to {$path}.");
        }
    }
}
