<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Eda\\Postgres\\PostgresHealthIndicator',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
            0 => [
                'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                'args' => [
                    0 => 'firefly.eda.provider',
                    1 => 'postgres',
                    2 => false,
                ],
            ],
        ],
        'beanConditions' => [
        ],
    ],
    1 => [
        'class' => 'Firefly\\Eda\\Postgres\\PostgresOutboxAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'subscriberRegistry',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'eventPublisher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'outboxPreCommitHook',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'domainEventDispatcher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'commandEventPublisher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'eventConsumer',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnProperty',
                        'args' => [
                            0 => 'firefly.eda.provider',
                            1 => 'postgres',
                            2 => false,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
