<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Eda\\Postgres\\PostgresHealthIndicator',
        'stereotype' => 'component',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 0,
        'qualifier' => null,
        'interfaces' => [
            0 => 'Firefly\\Actuator\\Health\\HealthIndicator',
        ],
        'beans' => [
        ],
        'lazy' => false,
        'dependencies' => [
            0 => 'Illuminate\\Database\\ConnectionResolverInterface',
        ],
    ],
    1 => [
        'class' => 'Firefly\\Eda\\Postgres\\PostgresOutboxAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 900,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'subscriberRegistry',
                'returns' => 'Firefly\\Eda\\Bus\\SubscriberRegistry',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            1 => [
                'method' => 'eventPublisher',
                'returns' => 'Firefly\\Eda\\EventPublisher',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                    1 => 'Illuminate\\Database\\ConnectionResolverInterface',
                    2 => 'Firefly\\Eda\\Bus\\SubscriberRegistry',
                ],
            ],
            2 => [
                'method' => 'outboxPreCommitHook',
                'returns' => 'Firefly\\Eda\\Postgres\\Outbox\\OutboxPreCommitHook',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Illuminate\\Database\\ConnectionResolverInterface',
                    1 => 'Firefly\\Config\\Config',
                    2 => 'Firefly\\Cqrs\\Handler\\HandlerManifest',
                    3 => 'Firefly\\Cqrs\\Correlation\\CorrelationContext',
                    4 => 'Firefly\\Eda\\Bus\\SubscriberRegistry',
                ],
            ],
            3 => [
                'method' => 'domainEventDispatcher',
                'returns' => 'Firefly\\Data\\Domain\\DomainEventDispatcher',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Data\\Domain\\AggregateTracker',
                    1 => 'Firefly\\Context\\Event\\ApplicationEventPublisher',
                    2 => 'Firefly\\Eda\\Postgres\\Outbox\\OutboxPreCommitHook',
                ],
            ],
            4 => [
                'method' => 'commandEventPublisher',
                'returns' => 'Firefly\\Cqrs\\Event\\CommandEventPublisher',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            5 => [
                'method' => 'eventConsumer',
                'returns' => 'Firefly\\Eda\\Consumer\\EventConsumer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Config\\Config',
                    1 => 'Illuminate\\Database\\ConnectionResolverInterface',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
];
