<?php

declare(strict_types=1);

namespace Firefly\Validation\Constraint;

use Firefly\Kernel\Exception\Framework\ConfigurationException;
use Firefly\Validation\Rule\DecimalScale;
use Illuminate\Contracts\Validation\ValidationRule;

/**
 * Compile-time façade over ConstraintScanner. Delegates the single reflection pass to the scanner, then
 * serialises each ValidationRule object into a var_export-safe envelope. The only arg-bearing shipped rule
 * is DecimalScale, so envelope() special-cases exactly it (via its additive scale() accessor); every other
 * rule serialises to a bare ['@rule' => Class]. Never called on the cached path.
 *
 * @phpstan-type RuleEnvelope array{'@rule': class-string<ValidationRule>, args?: list<mixed>}
 */
final class ConstraintManifestCompiler
{
    public function __construct(private readonly ConstraintScanner $scanner = new ConstraintScanner) {}

    /**
     * @param  list<class-string>  $classes
     * @return array<class-string, array<string, list<string|RuleEnvelope>>>
     */
    public function toArray(array $classes): array
    {
        $rows = [];
        foreach ($classes as $class) {
            $rows[$class] = $this->serialise($this->scanner->scan($class));
        }

        return $rows;
    }

    /**
     * @param  list<class-string>  $classes
     */
    public function compile(array $classes): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/validation. Do not edit.\n\nreturn "
            .var_export($this->toArray($classes), true)
            .";\n";
    }

    /**
     * @param  list<class-string>  $classes
     */
    public function write(array $classes, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($classes)) === false) {
            throw new ConfigurationException("Could not write constraint manifest to {$path}.");
        }
    }

    /**
     * @param  array<string, list<string|ValidationRule>>  $scanned
     * @return array<string, list<string|RuleEnvelope>>
     */
    private function serialise(array $scanned): array
    {
        $result = [];
        foreach ($scanned as $property => $rules) {
            $entries = [];
            foreach ($rules as $rule) {
                $entries[] = is_string($rule) ? $rule : $this->envelope($rule);
            }
            $result[$property] = $entries;
        }

        return $result;
    }

    /**
     * @return RuleEnvelope
     */
    private function envelope(ValidationRule $rule): array
    {
        if ($rule instanceof DecimalScale) {
            return ['@rule' => $rule::class, 'args' => [$rule->scale()]];
        }

        return ['@rule' => $rule::class];
    }
}
