<?php

declare(strict_types=1);

namespace Firefly\Tests\Browser\Support;

use Firefly\OpenApi\Tests\Support\FixtureDocument;
use Firefly\OpenApi\Web\ViewerPage;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Route;

/**
 * The built-in API reference (`firefly.openapi.viewer.style: builtin`) drawing a document that holds every
 * response shape the generator emits — firefly/openapi's ReturnFixture, generated by the real scanners.
 *
 * The skeleton's own document is too plain to prove the viewer: it has no union, no nullable nested object and
 * no map response beyond one greeting. So two test routes serve the REAL page ViewerPage renders for the
 * `builtin` style, pointed at the REAL document generated from the fixture — nothing hand-written on either
 * side, in the Chromium the rest of the suite drives.
 */
abstract class BuiltinViewerBrowserTestCase extends BrowserTestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        Route::get('/viewer-fixture/openapi.json', static fn (): Response => new Response(
            FixtureDocument::generatorFor('ReturnFixture')->toJson(),
            200,
            ['Content-Type' => 'application/json'],
        ));

        Route::get('/viewer-fixture', static fn (): Response => new Response(
            (new ViewerPage('Return shapes'))->render('/viewer-fixture/openapi.json', 'builtin'),
            200,
            ['Content-Type' => 'text/html; charset=UTF-8'],
        ));
    }
}
