<?php

declare(strict_types=1);

namespace Firefly\Context\Scanner;

use Firefly\Kernel\Exception\Framework\ConfigurationException;

final class ContextManifestCompiler
{
    /**
     * @param  list<ContextDescriptor>  $descriptors
     */
    public function compile(array $descriptors): string
    {
        $rows = array_map(static fn (ContextDescriptor $d): array => $d->toArray(), $descriptors);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by firefly/context. Do not edit.\n\nreturn "
            .var_export($rows, true)
            .";\n";
    }

    /**
     * @param  list<ContextDescriptor>  $descriptors
     */
    public function write(array $descriptors, string $path): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! mkdir($dir, 0o775, true) && ! is_dir($dir)) {
            throw new ConfigurationException("Could not create manifest directory {$dir}.");
        }

        if (file_put_contents($path, $this->compile($descriptors)) === false) {
            throw new ConfigurationException("Could not write context manifest to {$path}.");
        }
    }
}
