<?php

declare(strict_types=1);

// Generated by firefly/container. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Cqrs\\CqrsAutoConfiguration',
        'stereotype' => 'configuration',
        'name' => null,
        'scope' => 'Singleton',
        'primary' => false,
        'order' => 1000,
        'qualifier' => null,
        'interfaces' => [
        ],
        'beans' => [
            0 => [
                'method' => 'handlerRegistry',
                'returns' => 'Firefly\\Cqrs\\Handler\\HandlerRegistry',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            1 => [
                'method' => 'correlationContext',
                'returns' => 'Firefly\\Cqrs\\Correlation\\CorrelationContext',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            2 => [
                'method' => 'messageValidator',
                'returns' => 'Firefly\\Cqrs\\Validation\\MessageValidator',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Illuminate\\Container\\Container',
                ],
            ],
            3 => [
                'method' => 'commandAuthorizer',
                'returns' => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            4 => [
                'method' => 'queryAuthorizer',
                'returns' => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            5 => [
                'method' => 'cqrsMetrics',
                'returns' => 'Firefly\\Cqrs\\Metrics\\CqrsMetrics',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            6 => [
                'method' => 'queryCache',
                'returns' => 'Firefly\\Cqrs\\Cache\\QueryCache',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                ],
            ],
            7 => [
                'method' => 'commandEventPublisher',
                'returns' => 'Firefly\\Cqrs\\Event\\CommandEventPublisher',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Illuminate\\Container\\Container',
                    1 => 'Firefly\\Config\\Config',
                    2 => 'Firefly\\Cqrs\\Handler\\HandlerManifest',
                    3 => 'Firefly\\Cqrs\\Correlation\\CorrelationContext',
                ],
            ],
            8 => [
                'method' => 'domainEventBridge',
                'returns' => 'Firefly\\Cqrs\\Event\\DomainEventBridge',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Cqrs\\Event\\CommandEventPublisher',
                    1 => 'Firefly\\Config\\Config',
                    2 => 'Illuminate\\Container\\Container',
                ],
            ],
            9 => [
                'method' => 'commandBus',
                'returns' => 'Firefly\\Cqrs\\Command\\CommandBus',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Cqrs\\Handler\\HandlerRegistry',
                    1 => 'Firefly\\Cqrs\\Validation\\MessageValidator',
                    2 => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
                    3 => 'Firefly\\Cqrs\\Correlation\\CorrelationContext',
                    4 => 'Firefly\\Cqrs\\Metrics\\CqrsMetrics',
                ],
            ],
            10 => [
                'method' => 'queryBus',
                'returns' => 'Firefly\\Cqrs\\Query\\QueryBus',
                'name' => null,
                'scope' => 'Singleton',
                'primary' => false,
                'order' => 0,
                'lazy' => false,
                'dependencies' => [
                    0 => 'Firefly\\Cqrs\\Handler\\HandlerRegistry',
                    1 => 'Firefly\\Cqrs\\Validation\\MessageValidator',
                    2 => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
                    3 => 'Firefly\\Cqrs\\Correlation\\CorrelationContext',
                    4 => 'Firefly\\Cqrs\\Metrics\\CqrsMetrics',
                    5 => 'Firefly\\Cqrs\\Cache\\QueryCache',
                    6 => 'Firefly\\Config\\Config',
                ],
            ],
        ],
        'lazy' => false,
        'dependencies' => [
        ],
    ],
];
