<?php

declare(strict_types=1);

// Generated by firefly/context. Do not edit.

return [
    0 => [
        'class' => 'Firefly\\Cqrs\\CqrsAutoConfiguration',
        'postConstruct' => [
        ],
        'preDestroy' => [
        ],
        'listeners' => [
        ],
        'conditions' => [
        ],
        'beanConditions' => [
            0 => [
                'method' => 'handlerRegistry',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Handler\\HandlerRegistry',
                        ],
                    ],
                ],
            ],
            1 => [
                'method' => 'correlationContext',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Correlation\\CorrelationContext',
                        ],
                    ],
                ],
            ],
            2 => [
                'method' => 'messageValidator',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Validation\\MessageValidator',
                        ],
                    ],
                ],
            ],
            3 => [
                'method' => 'commandAuthorizer',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Security\\CommandAuthorizer',
                        ],
                    ],
                ],
            ],
            4 => [
                'method' => 'queryAuthorizer',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Security\\QueryAuthorizer',
                        ],
                    ],
                ],
            ],
            5 => [
                'method' => 'cqrsMetrics',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Metrics\\CqrsMetrics',
                        ],
                    ],
                ],
            ],
            6 => [
                'method' => 'queryCache',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Cache\\QueryCache',
                        ],
                    ],
                ],
            ],
            7 => [
                'method' => 'commandEventPublisher',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Event\\CommandEventPublisher',
                        ],
                    ],
                ],
            ],
            8 => [
                'method' => 'domainEventBridge',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Event\\DomainEventBridge',
                        ],
                    ],
                ],
            ],
            9 => [
                'method' => 'commandBus',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Command\\CommandBus',
                        ],
                    ],
                ],
            ],
            10 => [
                'method' => 'queryBus',
                'conditions' => [
                    0 => [
                        'type' => 'Firefly\\Context\\Condition\\Attributes\\ConditionalOnMissingBean',
                        'args' => [
                            0 => 'Firefly\\Cqrs\\Query\\QueryBus',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
