<?php

declare(strict_types=1);

namespace Firefly\OpenApi\Web;

use Firefly\OpenApi\OpenApiProperties;
use Illuminate\Contracts\Routing\UrlGenerator;
use Illuminate\Http\Response;

/**
 * Serves the human-facing API reference. The page fetches the spec from the sibling route rather than having
 * the document inlined into it, so a spec regenerated by an edit-and-reload cycle shows up on a browser
 * refresh, and so the two routes can be exposed independently (a deployment may want the machine-readable
 * document public and the console off, or the reverse).
 *
 * The spec URL is resolved through the UrlGenerator rather than concatenated, because an app mounted under a
 * subdirectory or behind APP_URL would otherwise get a link that 404s from every page but the root — and a
 * viewer whose only network call is wrong is a viewer that shows nothing at all.
 */
final class OpenApiViewerAction
{
    public function __construct(
        private readonly OpenApiProperties $properties,
        private readonly ViewerPage $page,
        private readonly UrlGenerator $urls,
    ) {}

    public function __invoke(): Response
    {
        return new Response(
            $this->page->render($this->urls->to($this->properties->specPath), $this->properties->viewerCdn),
            200,
            ['Content-Type' => 'text/html; charset=UTF-8'],
        );
    }
}
